CREATE TABLE "AKTEN_GELOESCHT"(
    "AKTENZEICHEN" VARCHAR2(32 BYTE) NOT NULL,
    PRIMARY KEY ("AKTENZEICHEN")
);
CREATE TABLE "PERSONEN_GELOESCHT"(
    "PERSONENNUMMER" NUMBER(10, 0) NOT NULL,
    "AKTENZEICHEN" VARCHAR2(32 BYTE),
    "AZRNUMMER" VARCHAR2(12 BYTE),
    PRIMARY KEY ("PERSONENNUMMER")
);