Insert into ANTRAGSTELLER (ANTRAGSTELLER_OID,PKZ,AKTENZEICHEN,AZRNUMMER,DNUMMER,ENUMMER,EURODACNR,FAMILIENNAME,VORNAME,GEBURTSDATUM,GEBURTSLAND,GEBURTSORT,HERKUNFTSLAND,ANTRAGSDATUM,ANTRAGSTYP,AUSSENSTELLE,GESCHLECHT,STAATSANGEHOERIGKEIT,DATE_MODIFIED,CHANGED) values ('1','1','0000002',null,'D000000000003','null','null','Mustermann','Max',to_date('31.12.1964','DD.MM.YYYY'),'Westeros','Winterfell','1',to_date('31.12.2001','DD.MM.YYYY'),'Asylerstantrag (Art.16a+§3)','DU 5 Dublinverfahren','M','Westeros',to_date('31.12.2017','DD.MM.YYYY'),1);
Insert into ANTRAGSTELLER (ANTRAGSTELLER_OID,PKZ,AKTENZEICHEN,AZRNUMMER,DNUMMER,ENUMMER,EURODACNR,FAMILIENNAME,VORNAME,GEBURTSDATUM,GEBURTSLAND,GEBURTSORT,HERKUNFTSLAND,ANTRAGSDATUM,ANTRAGSTYP,AUSSENSTELLE,GESCHLECHT,STAATSANGEHOERIGKEIT,DATE_MODIFIED,CHANGED) values ('2','2','0000006',null,'D0000000000010','null','null','Novak','Peter',to_date('31.12.1974','DD.MM.YYYY'),'Westeros','Winterfell','1',to_date('31.12.2005','DD.MM.YYYY'),'Asylerstantrag (Art.16a+§3)','DU 5 Dublinverfahren','M','Westeros',to_date('31.12.2016','DD.MM.YYYY'),0);

Insert into BILD (OID,ANTRAGSTELLER_OID) values ('10','1');
Insert into BILD (OID,ANTRAGSTELLER_OID) values ('11','2');

Insert into AKTENREFERENZ (AKTENREFERENZ_OID,AKTENZEICHEN_A,AKTENZEICHEN_B,REFERENZBEZEICHNUNG,DATE_MODIFIED) values ('100','0000001','0000002','Akte',to_date('31.12.2017','DD.MM.YYYY'));

commit;