import { WorkplaceResponse } from '../workplace/workplace-response.model';
import { Status } from '../status/status.model';
import { Priority } from '../priority/priority.model';
import { IncidentHistory } from './incident-history.model';

export class IncidentResponse {
  caseId: number;
  probeId: number;
  galleryId: number;
  workplace: WorkplaceResponse;
  referenceType: string;
  fileReference: number;
  status: Status;
  priority: Priority;
  note: string;
  workplaceNote: string;
  createdDate: number;
  aPkz: number;
  aDNumber: string;
  aLastName: string;
  aFirstName: string;
  aBirthDate: number;
  aGender: string;
  aNationality: string;
  aBirthPlace: string;
  aApplicantType: string;
  aAzrNumber: string;
  aFileNumber: string;
  aWorkplace: string;
  bPkz: number;
  bDNumber: string;
  bLastName: string;
  bFirstName: string;
  bBirthDate: number;
  bGender: string;
  bNationality: string;
  bBirthPlace: string;
  bApplicantType: string;
  bAzrNumber: string;
  bFileNumber: string;
  bWorkplace: string;
  bemLastChangedBy: string;
  bemLastChangedOn: string;
  ausLastChangedBy: string;
  ausLastChangedOn: string;
  incidentHistory: IncidentHistory[];
}
