connect DBSCANADMIN/dbscanadmin123;

GRANT SELECT, INSERT ON DBSCANADMIN.CASES TO LIBIASNEW;

GRANT SELECT, INSERT ON DBSCANADMIN.IMAGES TO LIBIASNEW;

GRANT SELECT ON DBSCANADMIN.CROSSIDENTIFICATIONRESULTS TO LIBIASNEW;

GRANT SELECT, INSERT ON DBSCANADMIN.IDENTIFICATIONPROBES TO LIBIASNEW;

GRANT SELECT ON DBSCANADMIN.IDENTIFICATIONRESULTS TO LIBIASNEW;

GRANT DELETE ON DBSCANADMIN.CASES TO LIBIASNEW;

GRANT DELETE ON DBSCANADMIN.IMAGES TO LIBIASNEW;

GRANT SELECT, DELETE ON DBSCANADMIN.FIR_18_2 TO LIBIASNEW;

disconnect;
