------------------- FIR ----------------------
ALTER TABLE FIR_18_2 RENAME TO FIR_20_0;
ALTER TABLE FIR_20_0 ADD FIRRef VARCHAR(255);

ALTER TABLE FIR_20_0 RENAME CONSTRAINT R_FIR_18_2_CID TO R_FIR_20_0_CID;
ALTER TABLE FIR_20_0 RENAME CONSTRAINT U_FIR_18_2_CID TO U_FIR_20_0_CID;
ALTER TABLE FIR_20_0 RENAME CONSTRAINT U_FIR_18_2_RID TO U_FIR_20_0_RID;

ALTER INDEX U_FIR_18_2_CID RENAME TO U_FIR_20_0_CID;
ALTER INDEX U_FIR_18_2_RID RENAME TO U_FIR_20_0_RID;
CREATE INDEX CI_FIR_20_0_IS ON FIR_20_0 (Issuer, Serial);

------------------- RepDeleted ----------------------
DROP INDEX I_RepDeleted_TableName;
DROP INDEX I_RepDeleted_Serial;
DROP INDEX I_RepDeleted_Issuer;

CREATE INDEX CI_RepDeleted_TIS ON RepDeleted (TableName, Issuer, Serial);

------------------- VerificationLogImages ----------------------
ALTER TABLE VerificationLogImages DROP COLUMN FIR_12_0;


------------------- FIR ----------------------
ALTER TABLE FIR_20_0 RENAME TO FIRs;

ALTER TABLE FIRs RENAME CONSTRAINT R_FIR_20_0_CID TO R_FIRs_CID;
ALTER TABLE FIRs RENAME CONSTRAINT U_FIR_20_0_CID TO U_FIRs_CID;
ALTER TABLE FIRs RENAME CONSTRAINT U_FIR_20_0_RID TO U_FIRs_RID;

ALTER INDEX U_FIR_20_0_CID RENAME TO U_FIRs_CID;
ALTER INDEX U_FIR_20_0_RID RENAME TO U_FIRs_RID;
ALTER INDEX CI_FIR_20_0_IS RENAME TO CI_FIRs_IS;


------------------- IdentificationLogImages ----------------------
ALTER TABLE IdentificationLogImages DROP COLUMN EyeConfidence;
ALTER TABLE IdentificationLogImages ADD Confidence REAL;

------------------- Images ----------------------
ALTER TABLE Images DROP COLUMN EyeConfidence;
ALTER TABLE Images ADD Confidence REAL;

ALTER TABLE Images ADD Producer VARCHAR(255);
ALTER TABLE Images ADD IsReferenceImage INTEGER;
ALTER TABLE Images ADD Width REAL;
ALTER TABLE Images ADD Height REAL;
ALTER TABLE Images ADD Alpha REAL;
ALTER TABLE Images ADD CenterX REAL;
ALTER TABLE Images ADD CenterY REAL;
ALTER TABLE Images ADD MouthCornerLX REAL;
ALTER TABLE Images ADD MouthCornerLY REAL;
ALTER TABLE Images ADD MouthCornerRX REAL;
ALTER TABLE Images ADD MouthCornerRY REAL;
ALTER TABLE Images ADD NoseTipX REAL;
ALTER TABLE Images ADD NoseTipY REAL;

------------------- RepDeleted ----------------------
ALTER TABLE RepDeleted ADD DeletionTime TIMESTAMP;
CREATE INDEX CI_RepDeleted_DT ON RepDeleted (DeletionTime);


UPDATE CASES SET SERIAL = NULL;
UPDATE IMAGES SET SERIAL = NULL;

ALTER TABLE CASES MODIFY SERIAL NUMBER(19);
ALTER TABLE IMAGES MODIFY SERIAL NUMBER(19);
ALTER TABLE FIRS MODIFY SERIAL NUMBER(19);
ALTER TABLE REPTV MODIFY SERIAL NUMBER(19);
ALTER TABLE REPDELETED MODIFY SERIAL NUMBER(19);

ALTER TABLE FIRS DROP COLUMN DURATION;
ALTER TABLE FIRS DROP COLUMN QUALITY;

UPDATE CASES SET SERIAL = 1;
UPDATE IMAGES SET SERIAL = 1;
