ALTER TABLE INCIDENT ADD (
  BEM_LAST_CHANGED_BY      VARCHAR2(100 BYTE),
  BEM_LAST_CHANGED_ON      DATE,
  AUS_BEM_LAST_CHANGED_BY  VARCHAR2(100 BYTE),
  AUS_BEM_LAST_CHANGED_ON  DATE
);

CREATE TABLE INCIDENT_HISTORY (
  HISTORY_ID  NUMBER(10),
  CASE_ID     NUMBER(10),
  CHANGED_BY  VARCHAR2(100 BYTE),
  CHANGED_ON  DATE,
  TYPE        CHAR(1)
);

ALTER TABLE INCIDENT_HISTORY MODIFY (HISTORY_ID NOT NULL ENABLE);
ALTER TABLE INCIDENT_HISTORY MODIFY (CASE_ID NOT NULL ENABLE);

ALTER TABLE INCIDENT_HISTORY ADD CONSTRAINT INCIDENT_HISTORY_PK
PRIMARY KEY (HISTORY_ID) USING INDEX;

ALTER TABLE INCIDENT_HISTORY ADD CONSTRAINT INCIDENT_HISTORY_FK
FOREIGN KEY (CASE_ID) REFERENCES INCIDENT (CASE_ID) ENABLE;
