ALTER TABLE BILD ADD (
    GES_DATE_CREATED DATE,
    GES_DATE_DELETED DATE
);


CREATE TABLE GES_INCIDENT (
    CASE_ID                  NUMBER(10)     NOT NULL,
    PROBE_ID                 NUMBER(10)     NOT NULL,
    GALLERY_ID               NUMBER(10)     NOT NULL,
    SCORE                    BINARY_DOUBLE  NOT NULL,
    RANK                     NUMBER(3),
    JOB_ID                   VARCHAR2(20)   NOT NULL,
    DATE_CREATED             DATE,
    FILTER                   NUMBER(3),
    PRIORITY_ID              NUMBER(10)     DEFAULT 3,
    DIENSTSTELLE_ID          VARCHAR2(32),
    STATUS_ID                NUMBER(10)     DEFAULT 1,
    BEMERKUNG                VARCHAR2(1000),
    AUSSENSTELLE_BEMERKUNG   VARCHAR2(1000),
    AKTENREFERENZ_OID        NUMBER(10),
    REFERENZBEZEICHNUNG      VARCHAR2(64),
    A_ANTRAGSTELLER_OID      NUMBER(10),
    A_PKZ                    NUMBER(10),
    A_AKTENZEICHEN           VARCHAR2(32),
    A_AZRNUMMER              VARCHAR2(12),
    A_DNUMMER                VARCHAR2(128),
    A_ENUMMER                VARCHAR2(128),
    A_EURODACNR              VARCHAR2(128),
    A_FAMILIENNAME           VARCHAR2(64),
    A_VORNAME                VARCHAR2(64),
    A_GEBURTSDATUM           DATE,
    A_GEBURTSORT             VARCHAR2(128),
    A_HERKUNFTSLAND          VARCHAR2(128),
    A_GEBURTSLAND            VARCHAR2(128),
    A_ANTRAGSDATUM           DATE,
    A_ANTRAGSTYP             VARCHAR2(64),
    A_AUSSENSTELLE           VARCHAR2(64),
    A_GESCHLECHT             VARCHAR2(1),
    A_STAATSANGEHOERIGKEIT   VARCHAR2(128),
    A_DATE_MODIFIED          DATE,
    A_PROTECTED              NUMBER(3),
    B_ANTRAGSTELLER_OID      NUMBER(10),
    B_PKZ                    NUMBER(10),
    B_AKTENZEICHEN           VARCHAR2(32),
    B_AZRNUMMER              VARCHAR2(12),
    B_DNUMMER                VARCHAR2(128),
    B_ENUMMER                VARCHAR2(128),
    B_EURODACNR              VARCHAR2(128),
    B_FAMILIENNAME           VARCHAR2(64),
    B_VORNAME                VARCHAR2(64),
    B_GEBURTSDATUM           DATE,
    B_GEBURTSORT             VARCHAR2(128),
    B_HERKUNFTSLAND          VARCHAR2(128),
    B_GEBURTSLAND            VARCHAR2(128),
    B_ANTRAGSDATUM           DATE,
    B_ANTRAGSTYP             VARCHAR2(64),
    B_AUSSENSTELLE           VARCHAR2(64),
    B_GESCHLECHT             VARCHAR2(1),
    B_STAATSANGEHOERIGKEIT   VARCHAR2(128),
    B_DATE_MODIFIED          DATE,
    B_PROTECTED              NUMBER(3),
    BEM_LAST_CHANGED_BY      VARCHAR2(100),
    BEM_LAST_CHANGED_ON      DATE,
    AUS_BEM_LAST_CHANGED_BY  VARCHAR2(100),
    AUS_BEM_LAST_CHANGED_ON  DATE,
    A_PERSON_DELETED         DATE,
    B_PERSON_DELETED         DATE,
    A_AKTE_DELETED           DATE,
    B_AKTE_DELETED           DATE,
    STATUS_LAST_CHANGED_ON   DATE,
    A_AKTE_LOCKED            DATE,
    B_AKTE_LOCKED            DATE
);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT GES_INCIDENT_PK
    PRIMARY KEY (CASE_ID) USING INDEX;

ALTER TABLE GES_INCIDENT ADD CONSTRAINT CHK_GES_CASEID_POS
    CHECK (CASE_ID > 0);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT CHK_GES_RANK_POS
    CHECK (RANK > 0);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT CHK_GES_STATUS_POS
    CHECK (STATUS_ID > 0);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT CHK_GES_PRIORITY_POS
    CHECK (PRIORITY_ID > 0);

ALTER TABLE GES_INCIDENT MODIFY CONSTRAINT CHK_GES_PRIORITY_POS DISABLE;

ALTER TABLE GES_INCIDENT ADD CONSTRAINT GES_INCIDENT_GALLERYID_BILD_FK
    FOREIGN KEY (GALLERY_ID) REFERENCES BILD (OID);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT GES_INCIDENT_PROBEID_BILD_FK
    FOREIGN KEY (PROBE_ID) REFERENCES BILD (OID);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT GES_INCIDENT_PRIORITIES_FK
    FOREIGN KEY (PRIORITY_ID) REFERENCES PRIORITY (PRIORITY_ID);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT GES_INCIDENT_STATUS_FK
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (STATUS_ID);

ALTER TABLE GES_INCIDENT ADD CONSTRAINT GES_INCIDENT_DIENSTSTELLE_FK
    FOREIGN KEY (DIENSTSTELLE_ID) REFERENCES DIENSTSTELLE (ID);

CREATE INDEX GES_INCIDENT_AKTENREF_OID ON GES_INCIDENT (AKTENREFERENZ_OID);
CREATE INDEX GES_INCIDENT_A_AKTENZEICHEN ON GES_INCIDENT (A_AKTENZEICHEN);
CREATE INDEX GES_INCIDENT_A_ANTRAGSTELLER ON GES_INCIDENT (A_ANTRAGSTELLER_OID);
CREATE INDEX GES_INCIDENT_A_DNUMMER ON GES_INCIDENT (A_DNUMMER);
CREATE INDEX GES_INCIDENT_A_PKZ ON GES_INCIDENT (A_PKZ);
CREATE INDEX GES_INCIDENT_B_AKTENZEICHEN ON GES_INCIDENT (B_AKTENZEICHEN);
CREATE INDEX GES_INCIDENT_B_ANTRAGSTELLER ON GES_INCIDENT (B_ANTRAGSTELLER_OID);
CREATE INDEX GES_INCIDENT_B_DNUMMER ON GES_INCIDENT (B_DNUMMER);
CREATE INDEX GES_INCIDENT_B_PKZ ON GES_INCIDENT (B_PKZ);
CREATE INDEX GES_INCIDENT_FILTER ON GES_INCIDENT (FILTER);
CREATE INDEX GES_INCIDENT_GID ON GES_INCIDENT (GALLERY_ID);
CREATE INDEX GES_INCIDENT_OVERVIEW ON GES_INCIDENT (FILTER, PRIORITY_ID, STATUS_ID, CASE_ID DESC);
CREATE INDEX GES_INCIDENT_PID ON GES_INCIDENT (PROBE_ID);
CREATE INDEX GES_INCIDENT_PRID ON GES_INCIDENT (PRIORITY_ID);
CREATE INDEX GES_INCIDENT_SID ON GES_INCIDENT (STATUS_ID);

CREATE SEQUENCE GES_INCIDENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER GES_INCIDENT_SEQ_TR BEFORE INSERT ON GES_INCIDENT
FOR EACH ROW WHEN (NEW.CASE_ID IS NULL) BEGIN
  SELECT GES_INCIDENT_SEQ.NEXTVAL INTO :NEW.CASE_ID FROM DUAL;
END;
/

ALTER TRIGGER GES_INCIDENT_SEQ_TR DISABLE;

CREATE OR REPLACE TRIGGER GES_INCIDENT_BEFORE_UPDATE BEFORE UPDATE ON GES_INCIDENT
FOR EACH ROW WHEN (NEW.STATUS_ID <> OLD.STATUS_ID) BEGIN
  :NEW.STATUS_LAST_CHANGED_ON := SYSDATE;
END;
/


CREATE TABLE GES_INCIDENT_HISTORY (
    HISTORY_ID  NUMBER(10)  NOT NULL,
    CASE_ID     NUMBER(10)  NOT NULL,
    CHANGED_BY  VARCHAR2(100),
    CHANGED_ON  DATE,
    TYPE        CHAR(1)
);

ALTER TABLE GES_INCIDENT_HISTORY ADD CONSTRAINT GES_INCIDENT_HISTORY_PK
    PRIMARY KEY (HISTORY_ID) USING INDEX;

ALTER TABLE GES_INCIDENT_HISTORY ADD CONSTRAINT GES_INCIDENT_HISTORY_FK
    FOREIGN KEY (CASE_ID) REFERENCES GES_INCIDENT (CASE_ID);


CREATE TABLE SEARCH_REQUEST (
    REQUEST_ID            NUMBER(10)  NOT NULL,  -- Vorgangsnummer
    DATE_CREATED          DATE,                  -- Erstellt am (Suchzeitpunkt)
    CREATED_BY            VARCHAR2(20),          -- Erstellt von (Sachbearbeiter)
    DATE_MODIFIED         DATE,                  -- Letzte Änderung am
    MODIFIED_BY           VARCHAR2(20),          -- Letzte Änderung von
    DIENSTSTELLE_ID       VARCHAR2(32),          -- Abteilung
    BILDDATEN             BLOB,                  -- Suchbild
    MAX_CANDIDATES        NUMBER(3),             -- Max. Kandidaten
    MIN_SCORE             BINARY_DOUBLE,         -- Min. Score
    MIN_AGE               NUMBER(3),             -- Min. Alter
    GESCHLECHT            VARCHAR2(1),           -- Geschlecht
    STAATSANGEHOERIGKEIT  VARCHAR2(128),         -- Staatsangehörigkeit
    BEMERKUNG             VARCHAR2(1000),        -- Bemerkung
    TRANSFORMATION        VARCHAR2(1000)         -- Bildoperationen
);

ALTER TABLE SEARCH_REQUEST ADD CONSTRAINT SEARCH_REQUEST_PK
    PRIMARY KEY (REQUEST_ID) USING INDEX;

ALTER TABLE SEARCH_REQUEST ADD CONSTRAINT SEARCH_REQUEST_DIENSTSTELLE_FK
    FOREIGN KEY (DIENSTSTELLE_ID) REFERENCES DIENSTSTELLE (ID);

CREATE SEQUENCE SEARCH_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOORDER NOCYCLE;


CREATE TABLE SEARCH_REQUEST_CANDIDATE (
    REQUEST_ID            NUMBER(10)  NOT NULL,  -- Vorgangsnummer
    RANK                  NUMBER(3)   NOT NULL,  -- Rank
    SCORE                 BINARY_DOUBLE,         -- Score
    BILD_OID              NUMBER(10),            -- BildOID
    ANTRAGSTELLER_OID     NUMBER(10),            -- AntragstellerOID
    PKZ                   NUMBER(10),            -- PKZ (Personenkennziffer)
    AKTENZEICHEN          VARCHAR2(32),          -- Aktenzeichen
    AZRNUMMER             VARCHAR2(12),          -- AZR-Nummer
    DNUMMER               VARCHAR2(128),         -- D-Nummer
    ENUMMER               VARCHAR2(128),         -- E-Nummer
    EURODACNR             VARCHAR2(128),         -- Eurodac-Nr
    FAMILIENNAME          VARCHAR2(64),          -- Familienname
    VORNAME               VARCHAR2(64),          -- Vorname
    GEBURTSDATUM          DATE,                  -- Geburtsdatum
    GEBURTSORT            VARCHAR2(128),         -- Geburtsort
    GEBURTSLAND           VARCHAR2(128),         -- Geburtsland
    HERKUNFTSLAND         VARCHAR2(128),         -- Herkunftsland
    ANTRAGSDATUM          DATE,                  -- Antragsdatum
    ANTRAGSTYP            VARCHAR2(64),          -- Antragstyp
    AUSSENSTELLE          VARCHAR2(64),          -- Außenstelle
    GESCHLECHT            VARCHAR2(1),           -- Geschlecht
    STAATSANGEHOERIGKEIT  VARCHAR2(128),         -- Staatsangehörigkeit
    DATE_MODIFIED         DATE,                  -- Änderungsdatum
    TRANSFORMATION        VARCHAR2(1000)         -- Bildoperationen
);

ALTER TABLE SEARCH_REQUEST_CANDIDATE ADD CONSTRAINT SEARCH_REQUEST_CANDIDATE_PK
    PRIMARY KEY (REQUEST_ID, RANK) USING INDEX;

ALTER TABLE SEARCH_REQUEST_CANDIDATE ADD CONSTRAINT SEARCH_REQUEST_CANDIDATE_FK
    FOREIGN KEY (REQUEST_ID) REFERENCES SEARCH_REQUEST (REQUEST_ID) ON DELETE CASCADE;

ALTER TABLE SEARCH_REQUEST_CANDIDATE ADD CONSTRAINT SEARCH_REQUEST_CANDIDATE_FK2
    FOREIGN KEY (BILD_OID) REFERENCES BILD (OID);


CREATE TABLE TRAFFIC_LIGHT (
    ROLE_ID         NUMBER(10)  NOT NULL,
    SCORE_FROM      BINARY_DOUBLE,
    SCORE_TO        BINARY_DOUBLE,
    COMMENT_RED     VARCHAR2(100),
    COMMENT_YELLOW  VARCHAR2(100),
    COMMENT_GREEN   VARCHAR2(100)
);

ALTER TABLE TRAFFIC_LIGHT ADD CONSTRAINT TRAFFIC_LIGHT_PK
    PRIMARY KEY (ROLE_ID) USING INDEX;
