CREATE TABLE NOTIFICATION (
  ID          NUMBER(10)      NOT NULL,
  TEXT        VARCHAR2(1000),
  VALID_FROM  DATE,
  VALID_TO    DATE,
  TIMESTAMP   TIMESTAMP,
  USERNAME    VARCHAR2(20)
);

ALTER TABLE NOTIFICATION ADD CONSTRAINT NOTIFICATION_PK
PRIMARY KEY (ID) USING INDEX;

CREATE SEQUENCE NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1
NOCACHE NOORDER NOCYCLE;
