CREATE TABLE IDENT_PROBES (
  PROBEID  VARCHAR2(255) NOT NULL,
  IMG      BLOB
);

CREATE TABLE IDENT_RESULTS (
  PROBEID               VARCHAR2(255) NOT NULL,
  GALLERYID             VARCHAR2(255) NOT NULL,
  RANK                  NUMBER(3),
  SCORE                 BINARY_DOUBLE,
  ANTRAGSTELLER_OID     NUMBER(10),
  PKZ                   NUMBER(10),
  AKTENZEICHEN          VARCHAR2(32),
  AZRNUMMER             VARCHAR2(12),
  DNUMMER               VARCHAR2(128),
  ENUMMER               VARCHAR2(128),
  EURODACNR             VARCHAR2(128),
  FAMILIENNAME          VARCHAR2(128),
  VORNAME               VARCHAR2(128),
  GEBURTSDATUM          DATE,
  GEBURTSLAND           VARCHAR2(128),
  GEBURTSORT            VARCHAR2(128),
  HERKUNFTSLAND         VARCHAR2(128),
  ANTRAGSDATUM          DATE,
  ANTRAGSTYP            VARCHAR2(128),
  AUSSENSTELLE          VARCHAR2(128),
  GESCHLECHT            VARCHAR2(1),
  STAATSANGEHOERIGKEIT  VARCHAR2(128),
  DATE_MODIFIED         DATE,
  PERS_DATA             VARCHAR2(4000)
);

ALTER TABLE STATUS ADD STATUS_TEXT VARCHAR2(60 BYTE);

UPDATE STATUS SET STATUS_TEXT = 'Offen' WHERE STATUS_ID = 1;
UPDATE STATUS SET STATUS_TEXT = 'Aktendublette - MFI/verd. FA' WHERE STATUS_ID = 2;
UPDATE STATUS SET STATUS_TEXT = 'Keine Aktendublette - Prüfung' WHERE STATUS_ID = 3;
UPDATE STATUS SET STATUS_TEXT = 'Ungeklärt - Prüfung' WHERE STATUS_ID = 4;
UPDATE STATUS SET STATUS_TEXT = 'Kein Bearbeitungsbedarf' WHERE STATUS_ID = 5;
UPDATE STATUS SET STATUS_TEXT = 'Akten ohne Verknüpfung' WHERE STATUS_ID = 6;
UPDATE STATUS SET STATUS_TEXT = 'Bereinigt' WHERE STATUS_ID = 7;
UPDATE STATUS SET STATUS_TEXT = 'Bereit zur QS' WHERE STATUS_ID = 8;
UPDATE STATUS SET STATUS_TEXT = 'Unterschiedliche D-Nummer' WHERE STATUS_ID = 9;
UPDATE STATUS SET STATUS_TEXT = 'Automatisch bereinigt' WHERE STATUS_ID = 10;

INSERT INTO DIENSTSTELLE (ID, DIENSTSTELLE, IDM_ROLE) VALUES ('031', 'AS Bochum', 'IDMS_LiBiAs_ASNutzer_AS_Bochum');

COMMIT;
