ALTER TABLE INCIDENT MODIFY A_GEBURTSORT VARCHAR2(128);
ALTER TABLE INCIDENT MODIFY A_GEBURTSLAND VARCHAR2(128);
ALTER TABLE INCIDENT MODIFY A_HERKUNFTSLAND VARCHAR2(128);
ALTER TABLE INCIDENT MODIFY A_STAATSANGEHOERIGKEIT VARCHAR2(128);

ALTER TABLE INCIDENT MODIFY B_GEBURTSORT VARCHAR2(128);
ALTER TABLE INCIDENT MODIFY B_GEBURTSLAND VARCHAR2(128);
ALTER TABLE INCIDENT MODIFY B_HERKUNFTSLAND VARCHAR2(128);
ALTER TABLE INCIDENT MODIFY B_STAATSANGEHOERIGKEIT VARCHAR2(128);


CREATE TABLE NATIONALITY (
  NATIONALITY_ID  NUMBER(3),
  NATIONALITY     VARCHAR2(128)
);

ALTER TABLE NATIONALITY ADD CONSTRAINT NATIONALITY_PK
PRIMARY KEY (NATIONALITY_ID) USING INDEX;

ALTER TABLE NATIONALITY MODIFY (NATIONALITY_ID NOT NULL ENABLE);
ALTER TABLE NATIONALITY MODIFY (NATIONALITY NOT NULL ENABLE);

CREATE INDEX NATIONALITY_NAME ON NATIONALITY (NATIONALITY);


INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (0, 'Deutschland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (120, 'Jugoslawien (SFRJ)');  -- Jugoslawien
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (121, 'Albanien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (122, 'Bosnien und Herzegowina');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (123, 'Andorra');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (124, 'Belgien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (125, 'Bulgarien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (126, 'Dänemark');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (127, 'Estland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (128, 'Finnland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (129, 'Frankreich');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (130, 'Kroatien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (131, 'Slowenien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (132, 'Serbien und Montenegro');
--INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (133, 'Serbien (einschließlich Kosovo)');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (134, 'Griechenland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (135, 'Irland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (136, 'Island');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (137, 'Italien');
--INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (138, 'Jugoslawien, Bundesrepublik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (139, 'Lettland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (140, 'Montenegro');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (141, 'Liechtenstein');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (142, 'Litauen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (143, 'Luxemburg');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (144, 'Nordmazedonien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (145, 'Malta');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (146, 'Moldau, Republik');  -- Moldau
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (147, 'Monaco');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (148, 'Niederlande');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (149, 'Norwegen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (150, 'Kosovo');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (151, 'Österreich');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (152, 'Polen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (153, 'Portugal');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (154, 'Rumänien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (155, 'Slowakei');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (156, 'San Marino');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (157, 'Schweden');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (158, 'Schweiz');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (159, 'Sowjetunion');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (160, 'Russische Föderation');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (161, 'Spanien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (162, 'Tschechoslowakei');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (163, 'Türkei');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (164, 'Tschechien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (165, 'Ungarn');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (166, 'Ukraine');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (167, 'Vatikanstadt');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (168, 'Vereinigtes Königreich');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (169, 'Weißrussland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (170, 'Serbien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (181, 'Zypern');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (185, 'Britische Überseegebiete');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (221, 'Algerien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (223, 'Angola');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (224, 'Eritrea');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (225, 'Äthiopien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (226, 'Lesotho');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (227, 'Botsuana');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (229, 'Benin');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (230, 'Dschibuti');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (231, 'Elfenbeinküste (Cote d Ivoire)');  -- Côte d’Ivoire
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (232, 'Nigeria');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (233, 'Simbabwe');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (236, 'Gabun');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (237, 'Gambia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (238, 'Ghana');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (239, 'Mauretanien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (242, 'Cabo Verde');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (243, 'Kenia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (244, 'Komoren');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (245, 'Kongo');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (246, 'Kongo, Demokratische Republik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (247, 'Liberia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (248, 'Libyen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (249, 'Madagaskar');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (251, 'Mali');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (252, 'Marokko');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (253, 'Mauritius');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (254, 'Mosambik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (255, 'Niger');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (256, 'Malawi');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (257, 'Sambia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (258, 'Burkina Faso');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (259, 'Guinea-Bissau');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (261, 'Guinea');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (262, 'Kamerun');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (263, 'Südafrika');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (265, 'Ruanda');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (267, 'Namibia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (268, 'São Tomé und Príncipe');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (269, 'Senegal');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (271, 'Seychellen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (272, 'Sierra Leone');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (273, 'Somalia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (274, 'Äquatorialguinea');
--INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (276, 'Sudan (einschließlich Südsudan)');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (277, 'Sudan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (278, 'Südsudan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (281, 'Eswatini');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (282, 'Tansania, Vereinigte Republik');  -- Tansania
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (283, 'Togo');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (284, 'Tschad');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (285, 'Tunesien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (286, 'Uganda');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (287, 'Ägypten');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (289, 'Zentralafrikanische Republik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (291, 'Burundi');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (320, 'Antigua und Barbuda');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (322, 'Barbados');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (323, 'Argentinien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (324, 'Bahamas');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (326, 'Bolivien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (327, 'Brasilien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (328, 'Guyana');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (330, 'Belize');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (332, 'Chile');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (333, 'Dominica');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (334, 'Costa Rica');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (335, 'Dominikanische Republik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (336, 'Ecuador');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (337, 'El Salvador');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (340, 'Grenada');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (345, 'Guatemala');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (346, 'Haiti');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (347, 'Honduras');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (348, 'Kanada');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (349, 'Kolumbien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (351, 'Kuba');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (353, 'Mexiko');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (354, 'Nicaragua');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (355, 'Jamaika');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (357, 'Panama');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (359, 'Paraguay');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (361, 'Peru');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (364, 'Suriname');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (365, 'Uruguay');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (366, 'St. Lucia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (367, 'Venezuela');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (368, 'Vereinigte Staaten v. Amerika');  -- Vereinigte Staaten
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (369, 'St. Vincent und die Grenadinen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (370, 'St. Kitts und Nevis');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (371, 'Trinidad und Tobago');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (411, 'Hongkong');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (412, 'China (Macau)');  -- Macau
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (421, 'Jemen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (422, 'Armenien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (423, 'Afghanistan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (424, 'Bahrain');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (425, 'Aserbaidschan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (426, 'Bhutan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (427, 'Myanmar');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (429, 'Brunei Darussalam');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (430, 'Georgien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (431, 'Sri Lanka');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (432, 'Vietnam');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (434, 'Korea, Demokratische Volksrepublik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (436, 'Indien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (437, 'Indonesien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (438, 'Irak');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (439, 'Iran, Islamische Republik');  -- Iran
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (441, 'Israel');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (442, 'Japan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (444, 'Kasachstan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (445, 'Jordanien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (446, 'Kambodscha');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (447, 'Katar');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (448, 'Kuwait');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (449, 'Laos');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (450, 'Kirgisistan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (451, 'Libanon');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (454, 'Malediven');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (456, 'Oman');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (457, 'Mongolei');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (458, 'Nepal');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (459, 'Pers. aus palästinensischen Gebieten (nicht als Staat anerkannt)');  -- Palästinensische Gebiete
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (460, 'Bangladesch');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (461, 'Pakistan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (462, 'Philippinen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (465, 'Taiwan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (467, 'Korea, Republik');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (469, 'Vereinigte Arabische Emirate');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (470, 'Tadschikistan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (471, 'Turkmenistan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (472, 'Saudi-Arabien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (474, 'Singapur');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (475, 'Syrien, Arabische Republik');  -- Syrien
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (476, 'Thailand');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (477, 'Usbekistan');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (479, 'China');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (482, 'Malaysia');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (483, 'Timor-Leste');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (523, 'Australien');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (524, 'Salomonen');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (526, 'Fidschi');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (530, 'Kiribati');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (531, 'Nauru');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (532, 'Vanuatu');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (536, 'Neuseeland');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (537, 'Palau');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (538, 'Papua-Neuguinea');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (540, 'Tuvalu');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (541, 'Tonga');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (543, 'Samoa');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (544, 'Marshallinseln');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (545, 'Mikronesien');
--INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (910, 'für interne Zwecke verwendet');
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (911, 'sonst. afrik. Staatsangeh.');  -- BAMF intern
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (912, 'sonst. asiat. Staatsangeh.');  -- BAMF intern
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (913, 'sonst. austral. Staatsangeh.');  -- BAMF intern
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (914, 'sonst. europ. Staatsangeh.');  -- BAMF intern
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (997, 'Staatenlos');  -- staatenlos
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (998, 'Ungeklärt');  -- ungeklärt
INSERT INTO NATIONALITY (NATIONALITY_ID, NATIONALITY) VALUES (999, 'ohne Angabe');  -- ohne Angabe (Staatsangehörigkeit)

COMMIT;
