ALTER TABLE LOG ADD (
    USERNAME VARCHAR2(20 BYTE)
);

UPDATE LOG L SET USERNAME = (SELECT BU.USERNAME FROM BAM_USER BU WHERE BU.USER_ID = L.USER_ID);
COMMIT;

ALTER TABLE LOG DROP CONSTRAINT LOGS_USER_FK;

ALTER TABLE LOG DROP COLUMN USER_ID;


ALTER TABLE REPORT ADD (
    USERNAME VARCHAR2(20 BYTE)
);

UPDATE REPORT R SET USERNAME = (SELECT BU.USERNAME FROM BAM_USER BU WHERE BU.USER_ID = R.CREATED_BY);
COMMIT;

ALTER TABLE REPORT DROP CONSTRAINT REPORT_BAM_USER_FK;

ALTER TABLE REPORT DROP COLUMN CREATED_BY;


ALTER TABLE BAM_USER DROP CONSTRAINT BAM_USER_FK1;
ALTER TABLE BAM_USER MODIFY (ACTIVE NULL);
ALTER TABLE BAM_USER MODIFY (LAST_NAME NULL);
ALTER TABLE BAM_USER MODIFY (FIRST_NAME NULL);
ALTER TABLE BAM_USER MODIFY (PASSWORD NULL);


ALTER TABLE DIENSTSTELLE ADD (
    IDM_ROLE VARCHAR2(64)
);

ALTER TABLE USER_ROLE ADD (
    IDM_ROLE VARCHAR2(64)
);

UPDATE USER_ROLE SET IDM_ROLE = 'IDMS_LiBiAs_Administrator' WHERE ROLE = 'ADMIN';
UPDATE USER_ROLE SET IDM_ROLE = 'IDMS_LiBiAs_Supervisor' WHERE ROLE = 'SUPERUSER';
UPDATE USER_ROLE SET IDM_ROLE = 'IDMS_LiBiAs_Benutzer' WHERE ROLE = 'USER';
UPDATE USER_ROLE SET IDM_ROLE = 'IDMS_LiBiAs_ASNutzer' WHERE ROLE = 'AUSSENSTELLEUSER';
UPDATE USER_ROLE SET IDM_ROLE = 'IDMS_LiBiAs_Vergleicher' WHERE ROLE = 'COMPARER';
UPDATE USER_ROLE SET IDM_ROLE = 'IDMS_LiBiAs_Sucher' WHERE ROLE = 'SEARCHER';
COMMIT;
