INSERT INTO PRIORITY (PRIORITY_ID, PRIORITY) VALUES (9, 'PRIORITY 9');

COMMIT;

ALTER TABLE INCIDENT ADD STATUS_LAST_CHANGED_ON DATE;

CREATE OR REPLACE TRIGGER INCIDENT_BEFORE_UPDATE BEFORE UPDATE ON INCIDENT
FOR EACH ROW WHEN (NEW.STATUS_ID <> OLD.STATUS_ID)
BEGIN
  :NEW.STATUS_LAST_CHANGED_ON := SYSDATE;
END;
/
