CREATE TABLE AKTE_LOCKED (
  AKTENZEICHEN   VARCHAR2(32)  NOT NULL,
  DATE_MODIFIED  DATE
);

ALTER TABLE AKTE_LOCKED ADD CONSTRAINT AKTE_LOCKED_PK
PRIMARY KEY (AKTENZEICHEN) USING INDEX;

ALTER TABLE INCIDENT ADD (
  A_AKTE_LOCKED DATE,
  B_AKTE_LOCKED DATE
);

ALTER TABLE INCIDENT MODIFY CONSTRAINT SYS_C007197 DISABLE; -- CHECK ("PRIORITY_ID" > 0)
ALTER TABLE PRIORITY MODIFY CONSTRAINT SYS_C007201 DISABLE; -- CHECK ("PRIORITY_ID" > 0)

INSERT INTO PRIORITY (PRIORITY_ID, PRIORITY) VALUES (0, '0: Aktentresor');
UPDATE PRIORITY SET PRIORITY = '1: höchste' WHERE PRIORITY_ID = 1;
UPDATE PRIORITY SET PRIORITY = '2: hohe' WHERE PRIORITY_ID = 2;
UPDATE PRIORITY SET PRIORITY = '3: mittlere' WHERE PRIORITY_ID = 3;
UPDATE PRIORITY SET PRIORITY = '9: Prüffall' WHERE PRIORITY_ID = 9;

COMMIT;
