ALTER TABLE LIBIASNEW.BILD ADD (
    DATE_DELETED DATE,
    ACTIVE NUMBER(1) DEFAULT 1
);

ALTER TABLE LIBIASNEW.INCIDENT ADD (
    A_PERSON_DELETED DATE,
    B_PERSON_DELETED DATE,
    A_AKTE_DELETED DATE,
    B_AKTE_DELETED DATE
);

COMMIT