server:
  port: 8761
  
spring:
  application:
    name: eureka
  jmx:
    default-domain: eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/