Insert into DIENSTSTELLE (ID,DIENSTSTELLE) values ('ID1','Office 1');

Insert into LOG_TYPE (TYPE_ID,TYPE) values (1,'CREATE_USER');
Insert into LOG_TYPE (TYPE_ID,TYPE) values (2,'UPDATE_USER');
Insert into LOG_TYPE (TYPE_ID,TYPE) values (3,'STATUS_CHANGE');

Insert into STATUS (STATUSID,STATUS) values (1,'OPEN');
Insert into STATUS (STATUSID,STATUS) values (2,'FILES_DOUBLET');
Insert into STATUS (STATUSID,STATUS) values (3,'FILES_NO_DOUBLET');
Insert into STATUS (STATUSID,STATUS) values (4,'NOT_CLEAR');
Insert into STATUS (STATUSID,STATUS) values (5,'NO_PROCESSING');
Insert into STATUS (STATUSID,STATUS) values (6,'FILES_NO_LINK');
Insert into STATUS (STATUSID,STATUS) values (7,'ADJUSTED');
Insert into STATUS (STATUSID,STATUS) values (8,'READY_TO_QA');
Insert into STATUS (STATUSID,STATUS) values (9,'DNUMBER_DIFF');

Insert into USER_ROLE (ROLE_ID,ROLE) values (1,'ADMIN');
Insert into USER_ROLE (ROLE_ID,ROLE) values (2,'SUPERUSER');
Insert into USER_ROLE (ROLE_ID,ROLE) values (3,'USER');
Insert into USER_ROLE (ROLE_ID,ROLE) values (4,'AUSSENSTELLEUSER');
Insert into USER_ROLE (ROLE_ID,ROLE) values (5,'COMPARER');
Insert into USER_ROLE (ROLE_ID,ROLE) values (6,'SEARCHER');

Insert into BAM_USER (USER_ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,ACTIVE,PUBLIC_SECRET,PRIVATE_SECRET,DIENSTSTELLE_ID)
values (1,'admin','$2a$10$S5TCGtMUnk/fZQd/GSYceOGdmhX97m1ONPRxWitV6T9cx4UpKNixC','admin','admin',1,'YTVhNmU1ZWYtYmM0Yi00YjhiLWE4NTgtNzFhNmM2ZmRmMzE0','MDA4ZTZlYTYtNDc4Ny00ODJhLThiYTUtNDcwY2VjMjgwZWJk','ID1');

Insert into USER_ROLE2BAM_USER (ROLE_ID,USER_ID) values (4,1);
Insert into USER_ROLE2BAM_USER (ROLE_ID,USER_ID) values (1,1);
Insert into USER_ROLE2BAM_USER (ROLE_ID,USER_ID) values (2,1);
Insert into USER_ROLE2BAM_USER (ROLE_ID,USER_ID) values (5,1);
Insert into USER_ROLE2BAM_USER (ROLE_ID,USER_ID) values (3,1);
Insert into USER_ROLE2BAM_USER (ROLE_ID,USER_ID) values (6,1);


Insert into ANTRAGSTELLER (OID,PKZ,DNUMMER,ENUMMER,EURODACNR,FAMILIENNAME,VORNAME,GEBURTSDATUM,GEBURTSLAND,HERKUNFTSLAND,ANTRAGSDATUM,ANTRAGSTYP,DATE_MODIFIED,AUSSENSTELLE,GESCHLECHT,JOBID,IMPORTED,STAATSANGEHOERIGKEIT,AZRNUMMER) values ('1','1','abc','abc','abc','Mustermann','Erika',to_date('01.01.70','DD.MM.RR'),'Deutschland','Deutschland',to_date('01.01.18','DD.MM.RR'),'abc',null,'ID1','W','1',to_timestamp('24.05.18 15:33:09,000000000','DD.MM.RR HH24:MI:SSXFF'),'Deutschland','abc');
Insert into ANTRAGSTELLER (OID,PKZ,DNUMMER,ENUMMER,EURODACNR,FAMILIENNAME,VORNAME,GEBURTSDATUM,GEBURTSLAND,HERKUNFTSLAND,ANTRAGSDATUM,ANTRAGSTYP,DATE_MODIFIED,AUSSENSTELLE,GESCHLECHT,JOBID,IMPORTED,STAATSANGEHOERIGKEIT,AZRNUMMER) values ('2','2','abc','abc','abc','Mustermann','Erika',to_date('01.01.70','DD.MM.RR'),'Deutschland','Deutschland',to_date('01.01.18','DD.MM.RR'),'abc',null,'ID1','W','1',to_timestamp('24.05.18 15:34:37,000000000','DD.MM.RR HH24:MI:SSXFF'),'Deutschland','abc');

Insert into BILD (OID,ANTRAGSTELLER_OID,AKTENZEICHEN,DATE_MODIFIED,PKZ,JOBID) values ('1','1',null,null,'1','1');
Insert into BILD (OID,ANTRAGSTELLER_OID,AKTENZEICHEN,DATE_MODIFIED,PKZ,JOBID) values ('2','2',null,null,'2','1');

Insert into CROSSIDENTIFICATIONCASES (CASEID,PROBEID,SCORE,RANK,GALLERYID,JOBID,STATUSID,FILTERED,AKTENREFERENZID,BEMERKUNG,DIENSTSTELLE_ID,AUSSENSTELLE_BEMERKUNG) values ('1','1','0,9','1','2','1','7','0',null,'sadasdasd',null,null);

commit;


CREATE MATERIALIZED VIEW  "INCIDENT_MV" ("CASE_ID", "PKZ_PROBEID", "PKZ_GALLERYID", "LAST_NAME", "FIRST_NAME", "NATIONALITY", "AZR_NUMBER", "BIRTH_DATE", "D_NUMBER", "GENDER", "LAST_NAME2", "FIRST_NAME2", "NATIONALITY2", "AZR_NUMBER2", "BIRTH_DATE2", "D_NUMBER2", "GENDER2", "FILE_NUMBER", "FILE_NUMBER2", "FILE_ID", "REFERENCE_NUMBER")
ORGANIZATION HEAP 
BUILD IMMEDIATE 
USING INDEX 
REFRESH FORCE ON DEMAND
USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
AS SELECT  DISTINCT
caseid AS case_id,
pkz_1 AS pkz_probeid,
pkz_2 AS pkz_galleryid,
FAMILIENNAME AS last_name,
vorname AS first_name,
STAATSANGEHOERIGKEIT AS nationality,
AZRNUMMER AS AZR_NUMBER,
Geburtsdatum AS birth_date,
DNUMMER AS D_NUMBER,    
GESCHLECHT AS gender,
FAMILIENNAME2 AS last_name2,
vorname2 AS first_name2,
STAATSANGEHOERIGKEIT2 AS nationality2,
AZRNUMMER2 AS AZR_NUMBER2,
Geburtsdatum2 AS birth_date2,
DNUMMER2 AS D_NUMBER2,    
GESCHLECHT2 AS gender2,
AKTENZEICHEN AS FILE_NUMBER,    
AKTENZEICHEN2 AS FILE_NUMBER2,    
AKTENREFERENZID AS FILE_ID,
REFERENZBEZEICHNUNG AS REFERENCE_NUMBER
FROM
	(
SELECT
			cs.caseid,
			b1.PKZ as PKZ_1,
			b2.PKZ as PKZ_2,
			a.FAMILIENNAME,
			a.vorname,
			a.STAATSANGEHOERIGKEIT,
			a.AZRNUMMER,
			a.Geburtsdatum,
			a.GESCHLECHT,            
			a.DNUMMER,
			aa.FAMILIENNAME as FAMILIENNAME2,
			aa.vorname AS vorname2,
			aa.STAATSANGEHOERIGKEIT AS STAATSANGEHOERIGKEIT2,
			aa.AZRNUMMER AS AZRNUMMER2,
			aa.Geburtsdatum AS Geburtsdatum2,
			aa.GESCHLECHT AS GESCHLECHT2,
			aa.DNUMMER AS DNUMMER2,
			b1.AKTENZEICHEN,            
			b2.AKTENZEICHEN AS AKTENZEICHEN2,        
			cs.AKTENREFERENZID,      
			r.REFERENZBEZEICHNUNG
		FROM
			CrossIdentificationCases cs
		JOIN Bild b1 ON
			cs.ProbeID = b1.OID
		JOIN Bild b2 ON
			cs.GALLERYID = b2.OID            
		JOIN Antragsteller a ON
			a.OID = b1.ANTRAGSTELLER_OID
		JOIN Antragsteller aa ON
			aa.OID = b2.ANTRAGSTELLER_OID
		LEFT OUTER JOIN AKTENREFERENZ r ON
			cs.AKTENREFERENZID = r.OID            
		WHERE
			cs.Filtered = 0
			);

COMMENT ON MATERIALIZED VIEW  "INCIDENT_MV"  IS 'snapshot table for snapshot  INCIDENT_MV';

