//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnalyzePortraitResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalyzePortraitResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="foundFace" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="successfulProcessed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="portraitCharacteristics" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}PortraitCharacteristics"/&gt;
 *         &lt;element name="isoCompliance" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}ISO-19794-5FullFrontalCompliance"/&gt;
 *         &lt;element name="featureSet" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}PortraitFeatureSet"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalyzePortraitResult", propOrder = {
        "foundFace",
    "successfulProcessed",
    "portraitCharacteristics",
    "isoCompliance",
    "featureSet"
})
public class AnalyzePortraitResult {

    protected boolean foundFace;
    protected boolean successfulProcessed;
    @XmlElement(required = true)
    protected PortraitCharacteristics portraitCharacteristics;
    @XmlElement(required = true)
    protected ISO197945FullFrontalCompliance isoCompliance;
    @XmlElement(required = true)
    protected PortraitFeatureSet featureSet;

    /**
     * Gets the value of the foundFace property.
     * 
     */
    public boolean isFoundFace() {
        return foundFace;
    }

    /**
     * Sets the value of the foundFace property.
     * 
     */
    public void setFoundFace(boolean value) {
        this.foundFace = value;
    }

    /**
     * Gets the value of the successfulProcessed property.
     * 
     */
    public boolean isSuccessfulProcessed() {
        return successfulProcessed;
    }

    /**
     * Sets the value of the successfulProcessed property.
     * 
     */
    public void setSuccessfulProcessed(boolean value) {
        this.successfulProcessed = value;
    }

    /**
     * Gets the value of the portraitCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link PortraitCharacteristics }
     *     
     */
    public PortraitCharacteristics getPortraitCharacteristics() {
        return portraitCharacteristics;
    }

    /**
     * Sets the value of the portraitCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortraitCharacteristics }
     *     
     */
    public void setPortraitCharacteristics(PortraitCharacteristics value) {
        this.portraitCharacteristics = value;
    }

    /**
     * Gets the value of the isoCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link ISO197945FullFrontalCompliance }
     *     
     */
    public ISO197945FullFrontalCompliance getIsoCompliance() {
        return isoCompliance;
    }

    /**
     * Sets the value of the isoCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO197945FullFrontalCompliance }
     *     
     */
    public void setIsoCompliance(ISO197945FullFrontalCompliance value) {
        this.isoCompliance = value;
    }

    /**
     * Gets the value of the featureSet property.
     * 
     * @return
     *     possible object is
     *     {@link PortraitFeatureSet }
     *     
     */
    public PortraitFeatureSet getFeatureSet() {
        return featureSet;
    }

    /**
     * Sets the value of the featureSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortraitFeatureSet }
     *     
     */
    public void setFeatureSet(PortraitFeatureSet value) {
        this.featureSet = value;
    }

}
