//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="annotatedImage" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}AnnotatedImage" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotatedImage"
})
@XmlRootElement(name = "analyze-portrait-annotated")
public class AnalyzePortraitAnnotated {

    @XmlElementRef(name = "annotatedImage", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<AnnotatedImage> annotatedImage;

    /**
     * Gets the value of the annotatedImage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *     
     */
    public JAXBElement<AnnotatedImage> getAnnotatedImage() {
        return annotatedImage;
    }

    /**
     * Sets the value of the annotatedImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *     
     */
    public void setAnnotatedImage(JAXBElement<AnnotatedImage> value) {
        this.annotatedImage = value;
    }

}
