//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotatedImageRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotatedImageRef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="imageURL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="faceLocation" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}FaceLocation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotatedImageRef", propOrder = {
        "imageURL",
        "faceLocation"
})
public class AnnotatedImageRef {

    @XmlElement(required = true)
    protected String imageURL;
    @XmlElement(required = true)
    protected FaceLocation faceLocation;

    /**
     * Gets the value of the imageURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageURL() {
        return imageURL;
    }

    /**
     * Sets the value of the imageURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageURL(String value) {
        this.imageURL = value;
    }

    /**
     * Gets the value of the faceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link FaceLocation }
     *     
     */
    public FaceLocation getFaceLocation() {
        return faceLocation;
    }

    /**
     * Sets the value of the faceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaceLocation }
     *     
     */
    public void setFaceLocation(FaceLocation value) {
        this.faceLocation = value;
    }

}
