//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BoundingBox complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BoundingBox"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="center" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position"/&gt;
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundingBox", propOrder = {
        "center",
        "width",
        "height",
        "alpha"
})
public class BoundingBox {

    @XmlElement(required = true)
    protected Position center;
    protected float width;
    protected float height;
    protected float alpha;

    /**
     * Gets the value of the center property.
     *
     * @return possible object is
     * {@link Position }
     */
    public Position getCenter() {
        return center;
    }

    /**
     * Sets the value of the center property.
     *
     * @param value allowed object is
     *              {@link Position }
     */
    public void setCenter(Position value) {
        this.center = value;
    }

    /**
     * Gets the value of the width property.
     */
    public float getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     */
    public void setWidth(float value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     */
    public float getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     */
    public void setHeight(float value) {
        this.height = value;
    }

    /**
     * Gets the value of the alpha property.
     */
    public float getAlpha() {
        return alpha;
    }

    /**
     * Sets the value of the alpha property.
     */
    public void setAlpha(float value) {
        this.alpha = value;
    }

}
