//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="eyes" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}EyesPos" minOccurs="0"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "eyes",
        "id"
})
@XmlRootElement(name = "createManualAnnotatedFaceLocation")
public class CreateManualAnnotatedFaceLocation {

    @XmlElementRef(name = "eyes", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<EyesPos> eyes;
    @XmlElementRef(name = "id", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<String> id;

    /**
     * Gets the value of the eyes property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link EyesPos }{@code >}
     */
    public JAXBElement<EyesPos> getEyes() {
        return eyes;
    }

    /**
     * Sets the value of the eyes property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link EyesPos }{@code >}
     */
    public void setEyes(JAXBElement<EyesPos> value) {
        this.eyes = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setId(JAXBElement<String> value) {
        this.id = value;
    }

}
