//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for EnrollmentResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnrollmentResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="processedImages" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}ImageProcessingInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="successfullEnrolled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnrollmentResult", propOrder = {
    "transactionId",
    "processedImages",
    "successfullEnrolled"
})
public class EnrollmentResult {

    @XmlElement(required = true)
    protected String transactionId;
    protected List<ImageProcessingInfo> processedImages;
    protected boolean successfullEnrolled;

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the processedImages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processedImages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessedImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageProcessingInfo }
     * 
     * 
     */
    public List<ImageProcessingInfo> getProcessedImages() {
        if (processedImages == null) {
            processedImages = new ArrayList<ImageProcessingInfo>();
        }
        return this.processedImages;
    }

    /**
     * Gets the value of the successfullEnrolled property.
     * 
     */
    public boolean isSuccessfullEnrolled() {
        return successfullEnrolled;
    }

    /**
     * Sets the value of the successfullEnrolled property.
     * 
     */
    public void setSuccessfullEnrolled(boolean value) {
        this.successfullEnrolled = value;
    }

}
