//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ethnicity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="Ethnicity"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="white"/&gt;
 *     &lt;enumeration value="black"/&gt;
 *     &lt;enumeration value="asian"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Ethnicity")
@XmlEnum
public enum Ethnicity {

    @XmlEnumValue("white")
    WHITE("white"),
    @XmlEnumValue("black")
    BLACK("black"),
    @XmlEnumValue("asian")
    ASIAN("asian");
    private final String value;

    Ethnicity(String v) {
        value = v;
    }

    public static Ethnicity fromValue(String v) {
        for (Ethnicity c: Ethnicity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
