//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EyesPos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EyesPos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="right" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position"/&gt;
 *         &lt;element name="left" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EyesPos", propOrder = {
    "right",
        "left"
})
public class EyesPos {

    @XmlElement(required = true)
    protected Position right;
    @XmlElement(required = true)
    protected Position left;

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setRight(Position value) {
        this.right = value;
    }

    /**
     * Gets the value of the left property.
     *
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     *
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setLeft(Position value) {
        this.left = value;
    }

}
