//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for FaceLocation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FaceLocation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="producer" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Producer"/&gt;
 *         &lt;element name="boundingBox" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}BoundingBox"/&gt;
 *         &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="rightEye" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position" minOccurs="0"/&gt;
 *         &lt;element name="leftEye" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position" minOccurs="0"/&gt;
 *         &lt;element name="noseTip" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position" minOccurs="0"/&gt;
 *         &lt;element name="rightMouthCorner" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position" minOccurs="0"/&gt;
 *         &lt;element name="leftMouthCorner" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FaceLocation", propOrder = {
        "producer",
        "boundingBox",
        "confidence",
        "rightEye",
        "leftEye",
        "noseTip",
        "rightMouthCorner",
        "leftMouthCorner"
})
public class FaceLocation {

    @XmlElement(required = true)
    protected Producer producer;
    @XmlElement(required = true)
    protected BoundingBox boundingBox;
    protected float confidence;
    @XmlElementRef(name = "rightEye", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<Position> rightEye;
    @XmlElementRef(name = "leftEye", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<Position> leftEye;
    @XmlElementRef(name = "noseTip", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<Position> noseTip;
    @XmlElementRef(name = "rightMouthCorner", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<Position> rightMouthCorner;
    @XmlElementRef(name = "leftMouthCorner", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<Position> leftMouthCorner;

    /**
     * Gets the value of the producer property.
     *
     * @return possible object is
     * {@link Producer }
     */
    public Producer getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     *
     * @param value allowed object is
     *              {@link Producer }
     */
    public void setProducer(Producer value) {
        this.producer = value;
    }

    /**
     * Gets the value of the boundingBox property.
     *
     * @return possible object is
     * {@link BoundingBox }
     */
    public BoundingBox getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     *
     * @param value allowed object is
     *              {@link BoundingBox }
     */
    public void setBoundingBox(BoundingBox value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the confidence property.
     */
    public float getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     */
    public void setConfidence(float value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the rightEye property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public JAXBElement<Position> getRightEye() {
        return rightEye;
    }

    /**
     * Sets the value of the rightEye property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public void setRightEye(JAXBElement<Position> value) {
        this.rightEye = value;
    }

    /**
     * Gets the value of the leftEye property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public JAXBElement<Position> getLeftEye() {
        return leftEye;
    }

    /**
     * Sets the value of the leftEye property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public void setLeftEye(JAXBElement<Position> value) {
        this.leftEye = value;
    }

    /**
     * Gets the value of the noseTip property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public JAXBElement<Position> getNoseTip() {
        return noseTip;
    }

    /**
     * Sets the value of the noseTip property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public void setNoseTip(JAXBElement<Position> value) {
        this.noseTip = value;
    }

    /**
     * Gets the value of the rightMouthCorner property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public JAXBElement<Position> getRightMouthCorner() {
        return rightMouthCorner;
    }

    /**
     * Sets the value of the rightMouthCorner property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public void setRightMouthCorner(JAXBElement<Position> value) {
        this.rightMouthCorner = value;
    }

    /**
     * Gets the value of the leftMouthCorner property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public JAXBElement<Position> getLeftMouthCorner() {
        return leftMouthCorner;
    }

    /**
     * Sets the value of the leftMouthCorner property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    public void setLeftMouthCorner(JAXBElement<Position> value) {
        this.leftMouthCorner = value;
    }

}
