//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="caseProperties" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}CaseProperties"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "caseProperties"
})
@XmlRootElement(name = "GetCasePropertiesResponse")
public class GetCasePropertiesResponse {

    @XmlElement(required = true)
    protected CaseProperties caseProperties;

    /**
     * Gets the value of the caseProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CaseProperties }
     *     
     */
    public CaseProperties getCaseProperties() {
        return caseProperties;
    }

    /**
     * Sets the value of the caseProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseProperties }
     *     
     */
    public void setCaseProperties(CaseProperties value) {
        this.caseProperties = value;
    }

}
