//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * image processing information
 * 
 * <p>Java class for ImageProcessingInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageProcessingInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="foundFace" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="faceLocation" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}FaceLocation"/&gt;
 *         &lt;element name="sampleRejected" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="rejectedReason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageProcessingInfo", propOrder = {
    "id",
        "foundFace",
        "faceLocation",
    "sampleRejected",
    "rejectedReason"
})
public class ImageProcessingInfo {

    @XmlElement(required = true)
    protected String id;
    protected boolean foundFace;
    @XmlElement(required = true)
    protected FaceLocation faceLocation;
    protected boolean sampleRejected;
    @XmlElement(required = true)
    protected String rejectedReason;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the foundFace property.
     * 
     */
    public boolean isFoundFace() {
        return foundFace;
    }

    /**
     * Sets the value of the foundFace property.
     * 
     */
    public void setFoundFace(boolean value) {
        this.foundFace = value;
    }

    /**
     * Gets the value of the faceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link FaceLocation }
     *     
     */
    public FaceLocation getFaceLocation() {
        return faceLocation;
    }

    /**
     * Sets the value of the faceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaceLocation }
     *     
     */
    public void setFaceLocation(FaceLocation value) {
        this.faceLocation = value;
    }

    /**
     * Gets the value of the sampleRejected property.
     * 
     */
    public boolean isSampleRejected() {
        return sampleRejected;
    }

    /**
     * Sets the value of the sampleRejected property.
     * 
     */
    public void setSampleRejected(boolean value) {
        this.sampleRejected = value;
    }

    /**
     * Gets the value of the rejectedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectedReason() {
        return rejectedReason;
    }

    /**
     * Sets the value of the rejectedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectedReason(String value) {
        this.rejectedReason = value;
    }

}
