//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * complience with the ISO_19794_5 FullFrontal standard
 * 
 * <p>Java class for ISO-19794-5FullFrontalCompliance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ISO-19794-5FullFrontalCompliance"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="onlyOneFaceVisible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="goodVerticalFacePosition" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="horizontallyCenteredFace" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="widthOfHead" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="lengthOfHead" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="widthOfHeadBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="lengthOfHeadBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="resolutionBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="goodExposure" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="goodGrayScaleProfile" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="backgroundUniformityBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isFrontal" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isFrontalBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isLightingUniform" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="eyesOpenBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="imageWidthToHeightBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isSharp" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mouthClosedBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="hasNaturalSkinColour" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="noHotSpots" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="eyesNotRed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="eyesGazeFrontalBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="noTintedGlasses" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isCompliant" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="isBestPractice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ISO-19794-5FullFrontalCompliance", propOrder = {
    "onlyOneFaceVisible",
    "goodVerticalFacePosition",
    "horizontallyCenteredFace",
    "widthOfHead",
    "lengthOfHead",
    "widthOfHeadBestPractice",
    "lengthOfHeadBestPractice",
    "resolution",
    "resolutionBestPractice",
    "goodExposure",
    "goodGrayScaleProfile",
    "backgroundUniformityBestPractice",
    "isFrontal",
    "isFrontalBestPractice",
    "isLightingUniform",
    "eyesOpenBestPractice",
    "imageWidthToHeightBestPractice",
    "isSharp",
    "mouthClosedBestPractice",
    "hasNaturalSkinColour",
    "noHotSpots",
    "eyesNotRed",
    "eyesGazeFrontalBestPractice",
    "noTintedGlasses",
    "isCompliant",
    "isBestPractice"
})
public class ISO197945FullFrontalCompliance {

    protected boolean onlyOneFaceVisible;
    protected boolean goodVerticalFacePosition;
    protected boolean horizontallyCenteredFace;
    protected boolean widthOfHead;
    protected boolean lengthOfHead;
    protected boolean widthOfHeadBestPractice;
    protected boolean lengthOfHeadBestPractice;
    protected boolean resolution;
    protected boolean resolutionBestPractice;
    protected boolean goodExposure;
    protected boolean goodGrayScaleProfile;
    protected boolean backgroundUniformityBestPractice;
    protected boolean isFrontal;
    protected boolean isFrontalBestPractice;
    protected boolean isLightingUniform;
    protected boolean eyesOpenBestPractice;
    protected boolean imageWidthToHeightBestPractice;
    protected boolean isSharp;
    protected boolean mouthClosedBestPractice;
    protected boolean hasNaturalSkinColour;
    protected boolean noHotSpots;
    protected boolean eyesNotRed;
    protected boolean eyesGazeFrontalBestPractice;
    protected boolean noTintedGlasses;
    protected boolean isCompliant;
    protected boolean isBestPractice;

    /**
     * Gets the value of the onlyOneFaceVisible property.
     * 
     */
    public boolean isOnlyOneFaceVisible() {
        return onlyOneFaceVisible;
    }

    /**
     * Sets the value of the onlyOneFaceVisible property.
     * 
     */
    public void setOnlyOneFaceVisible(boolean value) {
        this.onlyOneFaceVisible = value;
    }

    /**
     * Gets the value of the goodVerticalFacePosition property.
     * 
     */
    public boolean isGoodVerticalFacePosition() {
        return goodVerticalFacePosition;
    }

    /**
     * Sets the value of the goodVerticalFacePosition property.
     * 
     */
    public void setGoodVerticalFacePosition(boolean value) {
        this.goodVerticalFacePosition = value;
    }

    /**
     * Gets the value of the horizontallyCenteredFace property.
     * 
     */
    public boolean isHorizontallyCenteredFace() {
        return horizontallyCenteredFace;
    }

    /**
     * Sets the value of the horizontallyCenteredFace property.
     * 
     */
    public void setHorizontallyCenteredFace(boolean value) {
        this.horizontallyCenteredFace = value;
    }

    /**
     * Gets the value of the widthOfHead property.
     * 
     */
    public boolean isWidthOfHead() {
        return widthOfHead;
    }

    /**
     * Sets the value of the widthOfHead property.
     * 
     */
    public void setWidthOfHead(boolean value) {
        this.widthOfHead = value;
    }

    /**
     * Gets the value of the lengthOfHead property.
     * 
     */
    public boolean isLengthOfHead() {
        return lengthOfHead;
    }

    /**
     * Sets the value of the lengthOfHead property.
     * 
     */
    public void setLengthOfHead(boolean value) {
        this.lengthOfHead = value;
    }

    /**
     * Gets the value of the widthOfHeadBestPractice property.
     * 
     */
    public boolean isWidthOfHeadBestPractice() {
        return widthOfHeadBestPractice;
    }

    /**
     * Sets the value of the widthOfHeadBestPractice property.
     * 
     */
    public void setWidthOfHeadBestPractice(boolean value) {
        this.widthOfHeadBestPractice = value;
    }

    /**
     * Gets the value of the lengthOfHeadBestPractice property.
     * 
     */
    public boolean isLengthOfHeadBestPractice() {
        return lengthOfHeadBestPractice;
    }

    /**
     * Sets the value of the lengthOfHeadBestPractice property.
     * 
     */
    public void setLengthOfHeadBestPractice(boolean value) {
        this.lengthOfHeadBestPractice = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     */
    public boolean isResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     */
    public void setResolution(boolean value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the resolutionBestPractice property.
     * 
     */
    public boolean isResolutionBestPractice() {
        return resolutionBestPractice;
    }

    /**
     * Sets the value of the resolutionBestPractice property.
     * 
     */
    public void setResolutionBestPractice(boolean value) {
        this.resolutionBestPractice = value;
    }

    /**
     * Gets the value of the goodExposure property.
     * 
     */
    public boolean isGoodExposure() {
        return goodExposure;
    }

    /**
     * Sets the value of the goodExposure property.
     * 
     */
    public void setGoodExposure(boolean value) {
        this.goodExposure = value;
    }

    /**
     * Gets the value of the goodGrayScaleProfile property.
     * 
     */
    public boolean isGoodGrayScaleProfile() {
        return goodGrayScaleProfile;
    }

    /**
     * Sets the value of the goodGrayScaleProfile property.
     * 
     */
    public void setGoodGrayScaleProfile(boolean value) {
        this.goodGrayScaleProfile = value;
    }

    /**
     * Gets the value of the backgroundUniformityBestPractice property.
     * 
     */
    public boolean isBackgroundUniformityBestPractice() {
        return backgroundUniformityBestPractice;
    }

    /**
     * Sets the value of the backgroundUniformityBestPractice property.
     * 
     */
    public void setBackgroundUniformityBestPractice(boolean value) {
        this.backgroundUniformityBestPractice = value;
    }

    /**
     * Gets the value of the isFrontal property.
     * 
     */
    public boolean isIsFrontal() {
        return isFrontal;
    }

    /**
     * Sets the value of the isFrontal property.
     * 
     */
    public void setIsFrontal(boolean value) {
        this.isFrontal = value;
    }

    /**
     * Gets the value of the isFrontalBestPractice property.
     * 
     */
    public boolean isIsFrontalBestPractice() {
        return isFrontalBestPractice;
    }

    /**
     * Sets the value of the isFrontalBestPractice property.
     * 
     */
    public void setIsFrontalBestPractice(boolean value) {
        this.isFrontalBestPractice = value;
    }

    /**
     * Gets the value of the isLightingUniform property.
     * 
     */
    public boolean isIsLightingUniform() {
        return isLightingUniform;
    }

    /**
     * Sets the value of the isLightingUniform property.
     * 
     */
    public void setIsLightingUniform(boolean value) {
        this.isLightingUniform = value;
    }

    /**
     * Gets the value of the eyesOpenBestPractice property.
     * 
     */
    public boolean isEyesOpenBestPractice() {
        return eyesOpenBestPractice;
    }

    /**
     * Sets the value of the eyesOpenBestPractice property.
     * 
     */
    public void setEyesOpenBestPractice(boolean value) {
        this.eyesOpenBestPractice = value;
    }

    /**
     * Gets the value of the imageWidthToHeightBestPractice property.
     * 
     */
    public boolean isImageWidthToHeightBestPractice() {
        return imageWidthToHeightBestPractice;
    }

    /**
     * Sets the value of the imageWidthToHeightBestPractice property.
     * 
     */
    public void setImageWidthToHeightBestPractice(boolean value) {
        this.imageWidthToHeightBestPractice = value;
    }

    /**
     * Gets the value of the isSharp property.
     * 
     */
    public boolean isIsSharp() {
        return isSharp;
    }

    /**
     * Sets the value of the isSharp property.
     * 
     */
    public void setIsSharp(boolean value) {
        this.isSharp = value;
    }

    /**
     * Gets the value of the mouthClosedBestPractice property.
     * 
     */
    public boolean isMouthClosedBestPractice() {
        return mouthClosedBestPractice;
    }

    /**
     * Sets the value of the mouthClosedBestPractice property.
     * 
     */
    public void setMouthClosedBestPractice(boolean value) {
        this.mouthClosedBestPractice = value;
    }

    /**
     * Gets the value of the hasNaturalSkinColour property.
     * 
     */
    public boolean isHasNaturalSkinColour() {
        return hasNaturalSkinColour;
    }

    /**
     * Sets the value of the hasNaturalSkinColour property.
     * 
     */
    public void setHasNaturalSkinColour(boolean value) {
        this.hasNaturalSkinColour = value;
    }

    /**
     * Gets the value of the noHotSpots property.
     * 
     */
    public boolean isNoHotSpots() {
        return noHotSpots;
    }

    /**
     * Sets the value of the noHotSpots property.
     * 
     */
    public void setNoHotSpots(boolean value) {
        this.noHotSpots = value;
    }

    /**
     * Gets the value of the eyesNotRed property.
     * 
     */
    public boolean isEyesNotRed() {
        return eyesNotRed;
    }

    /**
     * Sets the value of the eyesNotRed property.
     * 
     */
    public void setEyesNotRed(boolean value) {
        this.eyesNotRed = value;
    }

    /**
     * Gets the value of the eyesGazeFrontalBestPractice property.
     * 
     */
    public boolean isEyesGazeFrontalBestPractice() {
        return eyesGazeFrontalBestPractice;
    }

    /**
     * Sets the value of the eyesGazeFrontalBestPractice property.
     * 
     */
    public void setEyesGazeFrontalBestPractice(boolean value) {
        this.eyesGazeFrontalBestPractice = value;
    }

    /**
     * Gets the value of the noTintedGlasses property.
     * 
     */
    public boolean isNoTintedGlasses() {
        return noTintedGlasses;
    }

    /**
     * Sets the value of the noTintedGlasses property.
     * 
     */
    public void setNoTintedGlasses(boolean value) {
        this.noTintedGlasses = value;
    }

    /**
     * Gets the value of the isCompliant property.
     * 
     */
    public boolean isIsCompliant() {
        return isCompliant;
    }

    /**
     * Sets the value of the isCompliant property.
     * 
     */
    public void setIsCompliant(boolean value) {
        this.isCompliant = value;
    }

    /**
     * Gets the value of the isBestPractice property.
     * 
     */
    public boolean isIsBestPractice() {
        return isBestPractice;
    }

    /**
     * Sets the value of the isBestPractice property.
     * 
     */
    public void setIsBestPractice(boolean value) {
        this.isBestPractice = value;
    }

}
