//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cognitec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindFacesImage_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "image");
    private final static QName _AnalyzePortraitAnnotatedAnnotatedImage_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "annotatedImage");
    private final static QName _FvdbAddCaseCaseID_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "caseID");
    private final static QName _FvdbAddCaseProperties_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "properties");
    private final static QName _EnrollmentDbAuthName_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "authName");
    private final static QName _EnrollmentSetCaseId_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "caseId");
    private final static QName _EnrollmentSetImgSet_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "imgSet");
    private final static QName _EnrollmentAnnotatedAImgSet_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "aImgSet");
    private final static QName _StartDBEnrollmentJobId_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "jobId");
    private final static QName _StartDBIdentificationFacility_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "facility");
    private final static QName _IdentificationOne2FewCaseIDSelectedCases_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "selectedCases");
    private final static QName _IdentificationBinningCaseIDBinningSQL_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "binningSQL");
    private final static QName _VerificationPortraitsImageA_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "imageA");
    private final static QName _VerificationPortraitsImageB_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "imageB");
    private final static QName _VerificationPortraitsAnnotatedAnnotatedImageA_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "annotatedImageA");
    private final static QName _VerificationPortraitsAnnotatedAnnotatedImageB_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "annotatedImageB");
    private final static QName _EstimateEyesPositionsLocation_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "location");
    private final static QName _CreateManualAnnotatedFaceLocationEyes_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "eyes");
    private final static QName _CreateManualAnnotatedFaceLocationId_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "id");
    private final static QName _FaceLocationRightEye_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "rightEye");
    private final static QName _FaceLocationLeftEye_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "leftEye");
    private final static QName _FaceLocationNoseTip_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "noseTip");
    private final static QName _FaceLocationRightMouthCorner_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "rightMouthCorner");
    private final static QName _FaceLocationLeftMouthCorner_QNAME = new QName("urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", "leftMouthCorner");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cognitec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Alive }
     * 
     */
    public Alive createAlive() {
        return new Alive();
    }

    /**
     * Create an instance of {@link AliveResponse }
     * 
     */
    public AliveResponse createAliveResponse() {
        return new AliveResponse();
    }

    /**
     * Create an instance of {@link FindFaces }
     * 
     */
    public FindFaces createFindFaces() {
        return new FindFaces();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link FindFacesResponse }
     * 
     */
    public FindFacesResponse createFindFacesResponse() {
        return new FindFacesResponse();
    }

    /**
     * Create an instance of {@link FaceLocations }
     * 
     */
    public FaceLocations createFaceLocations() {
        return new FaceLocations();
    }

    /**
     * Create an instance of {@link AnalyzePortrait }
     * 
     */
    public AnalyzePortrait createAnalyzePortrait() {
        return new AnalyzePortrait();
    }

    /**
     * Create an instance of {@link AnalyzePortraitResponse }
     * 
     */
    public AnalyzePortraitResponse createAnalyzePortraitResponse() {
        return new AnalyzePortraitResponse();
    }

    /**
     * Create an instance of {@link AnalyzePortraitResult }
     * 
     */
    public AnalyzePortraitResult createAnalyzePortraitResult() {
        return new AnalyzePortraitResult();
    }

    /**
     * Create an instance of {@link AnalyzePortraitAnnotated }
     * 
     */
    public AnalyzePortraitAnnotated createAnalyzePortraitAnnotated() {
        return new AnalyzePortraitAnnotated();
    }

    /**
     * Create an instance of {@link AnnotatedImage }
     * 
     */
    public AnnotatedImage createAnnotatedImage() {
        return new AnnotatedImage();
    }

    /**
     * Create an instance of {@link AnalyzePortraitAnnotatedResponse }
     * 
     */
    public AnalyzePortraitAnnotatedResponse createAnalyzePortraitAnnotatedResponse() {
        return new AnalyzePortraitAnnotatedResponse();
    }

    /**
     * Create an instance of {@link FvdbAddCase }
     * 
     */
    public FvdbAddCase createFvdbAddCase() {
        return new FvdbAddCase();
    }

    /**
     * Create an instance of {@link CaseProperties }
     * 
     */
    public CaseProperties createCaseProperties() {
        return new CaseProperties();
    }

    /**
     * Create an instance of {@link AddCaseResponse }
     * 
     */
    public AddCaseResponse createAddCaseResponse() {
        return new AddCaseResponse();
    }

    /**
     * Create an instance of {@link FvdbChangeCaseProperties }
     * 
     */
    public FvdbChangeCaseProperties createFvdbChangeCaseProperties() {
        return new FvdbChangeCaseProperties();
    }

    /**
     * Create an instance of {@link ChangeCaseResponse }
     * 
     */
    public ChangeCaseResponse createChangeCaseResponse() {
        return new ChangeCaseResponse();
    }

    /**
     * Create an instance of {@link FvdbCaseExists }
     * 
     */
    public FvdbCaseExists createFvdbCaseExists() {
        return new FvdbCaseExists();
    }

    /**
     * Create an instance of {@link FvdbCaseExistsResponse }
     * 
     */
    public FvdbCaseExistsResponse createFvdbCaseExistsResponse() {
        return new FvdbCaseExistsResponse();
    }

    /**
     * Create an instance of {@link FvdbDeleteCase }
     * 
     */
    public FvdbDeleteCase createFvdbDeleteCase() {
        return new FvdbDeleteCase();
    }

    /**
     * Create an instance of {@link DeleteCaseResponse }
     * 
     */
    public DeleteCaseResponse createDeleteCaseResponse() {
        return new DeleteCaseResponse();
    }

    /**
     * Create an instance of {@link FvdbDeleteFIR }
     * 
     */
    public FvdbDeleteFIR createFvdbDeleteFIR() {
        return new FvdbDeleteFIR();
    }

    /**
     * Create an instance of {@link DeleteFIRResponse }
     * 
     */
    public DeleteFIRResponse createDeleteFIRResponse() {
        return new DeleteFIRResponse();
    }

    /**
     * Create an instance of {@link FvdbGetReferenceImage }
     * 
     */
    public FvdbGetReferenceImage createFvdbGetReferenceImage() {
        return new FvdbGetReferenceImage();
    }

    /**
     * Create an instance of {@link ReferenceImageResponse }
     * 
     */
    public ReferenceImageResponse createReferenceImageResponse() {
        return new ReferenceImageResponse();
    }

    /**
     * Create an instance of {@link FvdbGetCaseProperties }
     * 
     */
    public FvdbGetCaseProperties createFvdbGetCaseProperties() {
        return new FvdbGetCaseProperties();
    }

    /**
     * Create an instance of {@link GetCasePropertiesResponse }
     * 
     */
    public GetCasePropertiesResponse createGetCasePropertiesResponse() {
        return new GetCasePropertiesResponse();
    }

    /**
     * Create an instance of {@link EnrollmentDb }
     * 
     */
    public EnrollmentDb createEnrollmentDb() {
        return new EnrollmentDb();
    }

    /**
     * Create an instance of {@link EnrollmentResponseDB }
     * 
     */
    public EnrollmentResponseDB createEnrollmentResponseDB() {
        return new EnrollmentResponseDB();
    }

    /**
     * Create an instance of {@link EnrollmentResult }
     * 
     */
    public EnrollmentResult createEnrollmentResult() {
        return new EnrollmentResult();
    }

    /**
     * Create an instance of {@link EnrollmentSet }
     * 
     */
    public EnrollmentSet createEnrollmentSet() {
        return new EnrollmentSet();
    }

    /**
     * Create an instance of {@link ImageSet }
     * 
     */
    public ImageSet createImageSet() {
        return new ImageSet();
    }

    /**
     * Create an instance of {@link EnrollmentResponseSET }
     * 
     */
    public EnrollmentResponseSET createEnrollmentResponseSET() {
        return new EnrollmentResponseSET();
    }

    /**
     * Create an instance of {@link EnrollmentRefset }
     * 
     */
    public EnrollmentRefset createEnrollmentRefset() {
        return new EnrollmentRefset();
    }

    /**
     * Create an instance of {@link StringList }
     * 
     */
    public StringList createStringList() {
        return new StringList();
    }

    /**
     * Create an instance of {@link EnrollmentResponseREFSET }
     * 
     */
    public EnrollmentResponseREFSET createEnrollmentResponseREFSET() {
        return new EnrollmentResponseREFSET();
    }

    /**
     * Create an instance of {@link EnrollmentAnnotated }
     * 
     */
    public EnrollmentAnnotated createEnrollmentAnnotated() {
        return new EnrollmentAnnotated();
    }

    /**
     * Create an instance of {@link AnnotatedImageSet }
     * 
     */
    public AnnotatedImageSet createAnnotatedImageSet() {
        return new AnnotatedImageSet();
    }

    /**
     * Create an instance of {@link EnrollmentResponseANN }
     * 
     */
    public EnrollmentResponseANN createEnrollmentResponseANN() {
        return new EnrollmentResponseANN();
    }

    /**
     * Create an instance of {@link EnrollmentSetRef }
     * 
     */
    public EnrollmentSetRef createEnrollmentSetRef() {
        return new EnrollmentSetRef();
    }

    /**
     * Create an instance of {@link ImageRefSet }
     * 
     */
    public ImageRefSet createImageRefSet() {
        return new ImageRefSet();
    }

    /**
     * Create an instance of {@link EnrollmentResponseSETRef }
     * 
     */
    public EnrollmentResponseSETRef createEnrollmentResponseSETRef() {
        return new EnrollmentResponseSETRef();
    }

    /**
     * Create an instance of {@link EnrollmentAnnotatedRef }
     * 
     */
    public EnrollmentAnnotatedRef createEnrollmentAnnotatedRef() {
        return new EnrollmentAnnotatedRef();
    }

    /**
     * Create an instance of {@link AnnotatedImageRefSet }
     * 
     */
    public AnnotatedImageRefSet createAnnotatedImageRefSet() {
        return new AnnotatedImageRefSet();
    }

    /**
     * Create an instance of {@link EnrollmentResponseANNRef }
     * 
     */
    public EnrollmentResponseANNRef createEnrollmentResponseANNRef() {
        return new EnrollmentResponseANNRef();
    }

    /**
     * Create an instance of {@link StartDBEnrollment }
     * 
     */
    public StartDBEnrollment createStartDBEnrollment() {
        return new StartDBEnrollment();
    }

    /**
     * Create an instance of {@link StartDBEnrollmentResponse }
     * 
     */
    public StartDBEnrollmentResponse createStartDBEnrollmentResponse() {
        return new StartDBEnrollmentResponse();
    }

    /**
     * Create an instance of {@link WaitForDBEnrollment }
     * 
     */
    public WaitForDBEnrollment createWaitForDBEnrollment() {
        return new WaitForDBEnrollment();
    }

    /**
     * Create an instance of {@link WaitForDBEnrollmentResponse }
     * 
     */
    public WaitForDBEnrollmentResponse createWaitForDBEnrollmentResponse() {
        return new WaitForDBEnrollmentResponse();
    }

    /**
     * Create an instance of {@link WaitForSync }
     * 
     */
    public WaitForSync createWaitForSync() {
        return new WaitForSync();
    }

    /**
     * Create an instance of {@link WaitForSyncResponse }
     * 
     */
    public WaitForSyncResponse createWaitForSyncResponse() {
        return new WaitForSyncResponse();
    }

    /**
     * Create an instance of {@link StartDBIdentification }
     * 
     */
    public StartDBIdentification createStartDBIdentification() {
        return new StartDBIdentification();
    }

    /**
     * Create an instance of {@link StartDBIdentificationResponse }
     * 
     */
    public StartDBIdentificationResponse createStartDBIdentificationResponse() {
        return new StartDBIdentificationResponse();
    }

    /**
     * Create an instance of {@link WaitForDBIdentification }
     * 
     */
    public WaitForDBIdentification createWaitForDBIdentification() {
        return new WaitForDBIdentification();
    }

    /**
     * Create an instance of {@link WaitForDBIdentificationResponse }
     * 
     */
    public WaitForDBIdentificationResponse createWaitForDBIdentificationResponse() {
        return new WaitForDBIdentificationResponse();
    }

    /**
     * Create an instance of {@link IdentificationCaseID }
     * 
     */
    public IdentificationCaseID createIdentificationCaseID() {
        return new IdentificationCaseID();
    }

    /**
     * Create an instance of {@link IdentCaseIDResponse }
     * 
     */
    public IdentCaseIDResponse createIdentCaseIDResponse() {
        return new IdentCaseIDResponse();
    }

    /**
     * Create an instance of {@link IdentificationResult }
     * 
     */
    public IdentificationResult createIdentificationResult() {
        return new IdentificationResult();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link IdentResponse }
     * 
     */
    public IdentResponse createIdentResponse() {
        return new IdentResponse();
    }

    /**
     * Create an instance of {@link IdentificationAnnotated }
     * 
     */
    public IdentificationAnnotated createIdentificationAnnotated() {
        return new IdentificationAnnotated();
    }

    /**
     * Create an instance of {@link IdentAnnotatedResponse }
     * 
     */
    public IdentAnnotatedResponse createIdentAnnotatedResponse() {
        return new IdentAnnotatedResponse();
    }

    /**
     * Create an instance of {@link IdentificationOne2FewCaseID }
     * 
     */
    public IdentificationOne2FewCaseID createIdentificationOne2FewCaseID() {
        return new IdentificationOne2FewCaseID();
    }

    /**
     * Create an instance of {@link IdentOne2FewCaseIDResponse }
     * 
     */
    public IdentOne2FewCaseIDResponse createIdentOne2FewCaseIDResponse() {
        return new IdentOne2FewCaseIDResponse();
    }

    /**
     * Create an instance of {@link IdentificationOne2Few }
     * 
     */
    public IdentificationOne2Few createIdentificationOne2Few() {
        return new IdentificationOne2Few();
    }

    /**
     * Create an instance of {@link IdentOne2FewResponse }
     * 
     */
    public IdentOne2FewResponse createIdentOne2FewResponse() {
        return new IdentOne2FewResponse();
    }

    /**
     * Create an instance of {@link IdentificationOne2FewAnnotated }
     * 
     */
    public IdentificationOne2FewAnnotated createIdentificationOne2FewAnnotated() {
        return new IdentificationOne2FewAnnotated();
    }

    /**
     * Create an instance of {@link IdentOne2FewAnnResponse }
     * 
     */
    public IdentOne2FewAnnResponse createIdentOne2FewAnnResponse() {
        return new IdentOne2FewAnnResponse();
    }

    /**
     * Create an instance of {@link IdentificationBinningCaseID }
     * 
     */
    public IdentificationBinningCaseID createIdentificationBinningCaseID() {
        return new IdentificationBinningCaseID();
    }

    /**
     * Create an instance of {@link IdentBinningCaseIDResponse }
     * 
     */
    public IdentBinningCaseIDResponse createIdentBinningCaseIDResponse() {
        return new IdentBinningCaseIDResponse();
    }

    /**
     * Create an instance of {@link IdentificationBinning }
     * 
     */
    public IdentificationBinning createIdentificationBinning() {
        return new IdentificationBinning();
    }

    /**
     * Create an instance of {@link IdentBinningResponse }
     * 
     */
    public IdentBinningResponse createIdentBinningResponse() {
        return new IdentBinningResponse();
    }

    /**
     * Create an instance of {@link IdentificationBinningAnnotated }
     * 
     */
    public IdentificationBinningAnnotated createIdentificationBinningAnnotated() {
        return new IdentificationBinningAnnotated();
    }

    /**
     * Create an instance of {@link IdentBinAnnResponse }
     * 
     */
    public IdentBinAnnResponse createIdentBinAnnResponse() {
        return new IdentBinAnnResponse();
    }

    /**
     * Create an instance of {@link Verification }
     * 
     */
    public Verification createVerification() {
        return new Verification();
    }

    /**
     * Create an instance of {@link VerificationResponse }
     * 
     */
    public VerificationResponse createVerificationResponse() {
        return new VerificationResponse();
    }

    /**
     * Create an instance of {@link VerificationResult }
     * 
     */
    public VerificationResult createVerificationResult() {
        return new VerificationResult();
    }

    /**
     * Create an instance of {@link VerificationAnnotated }
     * 
     */
    public VerificationAnnotated createVerificationAnnotated() {
        return new VerificationAnnotated();
    }

    /**
     * Create an instance of {@link VerificationAnnResponse }
     * 
     */
    public VerificationAnnResponse createVerificationAnnResponse() {
        return new VerificationAnnResponse();
    }

    /**
     * Create an instance of {@link VerificationPortraits }
     * 
     */
    public VerificationPortraits createVerificationPortraits() {
        return new VerificationPortraits();
    }

    /**
     * Create an instance of {@link VerificationPortraitsResponse }
     * 
     */
    public VerificationPortraitsResponse createVerificationPortraitsResponse() {
        return new VerificationPortraitsResponse();
    }

    /**
     * Create an instance of {@link VerificationPortraitsResult }
     * 
     */
    public VerificationPortraitsResult createVerificationPortraitsResult() {
        return new VerificationPortraitsResult();
    }

    /**
     * Create an instance of {@link VerificationPortraitsAnnotated }
     * 
     */
    public VerificationPortraitsAnnotated createVerificationPortraitsAnnotated() {
        return new VerificationPortraitsAnnotated();
    }

    /**
     * Create an instance of {@link VerificationPortraitsAnnotatedResponse }
     * 
     */
    public VerificationPortraitsAnnotatedResponse createVerificationPortraitsAnnotatedResponse() {
        return new VerificationPortraitsAnnotatedResponse();
    }

    /**
     * Create an instance of {@link EstimateEyesPositions }
     */
    public EstimateEyesPositions createEstimateEyesPositions() {
        return new EstimateEyesPositions();
    }

    /**
     * Create an instance of {@link FaceLocation }
     */
    public FaceLocation createFaceLocation() {
        return new FaceLocation();
    }

    /**
     * Create an instance of {@link EyesPosResponse }
     */
    public EyesPosResponse createEyesPosResponse() {
        return new EyesPosResponse();
    }

    /**
     * Create an instance of {@link EyesPos }
     */
    public EyesPos createEyesPos() {
        return new EyesPos();
    }

    /**
     * Create an instance of {@link CreateManualAnnotatedFaceLocation }
     */
    public CreateManualAnnotatedFaceLocation createCreateManualAnnotatedFaceLocation() {
        return new CreateManualAnnotatedFaceLocation();
    }

    /**
     * Create an instance of {@link FaceLocationResponse }
     */
    public FaceLocationResponse createFaceLocationResponse() {
        return new FaceLocationResponse();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link Producer }
     *
     */
    public Producer createProducer() {
        return new Producer();
    }

    /**
     * Create an instance of {@link BoundingBox }
     */
    public BoundingBox createBoundingBox() {
        return new BoundingBox();
    }

    /**
     * Create an instance of {@link AnnotatedImageRef }
     * 
     */
    public AnnotatedImageRef createAnnotatedImageRef() {
        return new AnnotatedImageRef();
    }

    /**
     * Create an instance of {@link PortraitEthnicityMeasurements }
     * 
     */
    public PortraitEthnicityMeasurements createPortraitEthnicityMeasurements() {
        return new PortraitEthnicityMeasurements();
    }

    /**
     * Create an instance of {@link PortraitCharacteristics }
     * 
     */
    public PortraitCharacteristics createPortraitCharacteristics() {
        return new PortraitCharacteristics();
    }

    /**
     * Create an instance of {@link ISO197945FullFrontalCompliance }
     * 
     */
    public ISO197945FullFrontalCompliance createISO197945FullFrontalCompliance() {
        return new ISO197945FullFrontalCompliance();
    }

    /**
     * Create an instance of {@link PortraitFeatureSet }
     * 
     */
    public PortraitFeatureSet createPortraitFeatureSet() {
        return new PortraitFeatureSet();
    }

    /**
     * Create an instance of {@link CaseProperty }
     * 
     */
    public CaseProperty createCaseProperty() {
        return new CaseProperty();
    }

    /**
     * Create an instance of {@link ImageProcessingInfo }
     * 
     */
    public ImageProcessingInfo createImageProcessingInfo() {
        return new ImageProcessingInfo();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link MatchSet }
     * 
     */
    public MatchSet createMatchSet() {
        return new MatchSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "image", scope = FindFaces.class)
    public JAXBElement<Image> createFindFacesImage(Image value) {
        return new JAXBElement<Image>(_FindFacesImage_QNAME, Image.class, FindFaces.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "image", scope = AnalyzePortrait.class)
    public JAXBElement<Image> createAnalyzePortraitImage(Image value) {
        return new JAXBElement<Image>(_FindFacesImage_QNAME, Image.class, AnalyzePortrait.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImage", scope = AnalyzePortraitAnnotated.class)
    public JAXBElement<AnnotatedImage> createAnalyzePortraitAnnotatedAnnotatedImage(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_AnalyzePortraitAnnotatedAnnotatedImage_QNAME, AnnotatedImage.class, AnalyzePortraitAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbAddCase.class)
    public JAXBElement<String> createFvdbAddCaseCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbAddCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseProperties }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CaseProperties }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "properties", scope = FvdbAddCase.class)
    public JAXBElement<CaseProperties> createFvdbAddCaseProperties(CaseProperties value) {
        return new JAXBElement<CaseProperties>(_FvdbAddCaseProperties_QNAME, CaseProperties.class, FvdbAddCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbChangeCaseProperties.class)
    public JAXBElement<String> createFvdbChangeCasePropertiesCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbChangeCaseProperties.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseProperties }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CaseProperties }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "properties", scope = FvdbChangeCaseProperties.class)
    public JAXBElement<CaseProperties> createFvdbChangeCasePropertiesProperties(CaseProperties value) {
        return new JAXBElement<CaseProperties>(_FvdbAddCaseProperties_QNAME, CaseProperties.class, FvdbChangeCaseProperties.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbCaseExists.class)
    public JAXBElement<String> createFvdbCaseExistsCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbCaseExists.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbDeleteCase.class)
    public JAXBElement<String> createFvdbDeleteCaseCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbDeleteCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbDeleteFIR.class)
    public JAXBElement<String> createFvdbDeleteFIRCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbDeleteFIR.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbGetReferenceImage.class)
    public JAXBElement<String> createFvdbGetReferenceImageCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbGetReferenceImage.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = FvdbGetCaseProperties.class)
    public JAXBElement<String> createFvdbGetCasePropertiesCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, FvdbGetCaseProperties.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = EnrollmentDb.class)
    public JAXBElement<String> createEnrollmentDbCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, EnrollmentDb.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = EnrollmentDb.class)
    public JAXBElement<String> createEnrollmentDbAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, EnrollmentDb.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseId", scope = EnrollmentSet.class)
    public JAXBElement<String> createEnrollmentSetCaseId(String value) {
        return new JAXBElement<String>(_EnrollmentSetCaseId_QNAME, String.class, EnrollmentSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageSet }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ImageSet }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "imgSet", scope = EnrollmentSet.class)
    public JAXBElement<ImageSet> createEnrollmentSetImgSet(ImageSet value) {
        return new JAXBElement<ImageSet>(_EnrollmentSetImgSet_QNAME, ImageSet.class, EnrollmentSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = EnrollmentSet.class)
    public JAXBElement<String> createEnrollmentSetAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, EnrollmentSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseId", scope = EnrollmentRefset.class)
    public JAXBElement<String> createEnrollmentRefsetCaseId(String value) {
        return new JAXBElement<String>(_EnrollmentSetCaseId_QNAME, String.class, EnrollmentRefset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "imgSet", scope = EnrollmentRefset.class)
    public JAXBElement<StringList> createEnrollmentRefsetImgSet(StringList value) {
        return new JAXBElement<StringList>(_EnrollmentSetImgSet_QNAME, StringList.class, EnrollmentRefset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = EnrollmentRefset.class)
    public JAXBElement<String> createEnrollmentRefsetAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, EnrollmentRefset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseId", scope = EnrollmentAnnotated.class)
    public JAXBElement<String> createEnrollmentAnnotatedCaseId(String value) {
        return new JAXBElement<String>(_EnrollmentSetCaseId_QNAME, String.class, EnrollmentAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImageSet }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImageSet }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "aImgSet", scope = EnrollmentAnnotated.class)
    public JAXBElement<AnnotatedImageSet> createEnrollmentAnnotatedAImgSet(AnnotatedImageSet value) {
        return new JAXBElement<AnnotatedImageSet>(_EnrollmentAnnotatedAImgSet_QNAME, AnnotatedImageSet.class, EnrollmentAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = EnrollmentAnnotated.class)
    public JAXBElement<String> createEnrollmentAnnotatedAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, EnrollmentAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseId", scope = EnrollmentSetRef.class)
    public JAXBElement<String> createEnrollmentSetRefCaseId(String value) {
        return new JAXBElement<String>(_EnrollmentSetCaseId_QNAME, String.class, EnrollmentSetRef.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageRefSet }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ImageRefSet }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "imgSet", scope = EnrollmentSetRef.class)
    public JAXBElement<ImageRefSet> createEnrollmentSetRefImgSet(ImageRefSet value) {
        return new JAXBElement<ImageRefSet>(_EnrollmentSetImgSet_QNAME, ImageRefSet.class, EnrollmentSetRef.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = EnrollmentSetRef.class)
    public JAXBElement<String> createEnrollmentSetRefAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, EnrollmentSetRef.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseId", scope = EnrollmentAnnotatedRef.class)
    public JAXBElement<String> createEnrollmentAnnotatedRefCaseId(String value) {
        return new JAXBElement<String>(_EnrollmentSetCaseId_QNAME, String.class, EnrollmentAnnotatedRef.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImageRefSet }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImageRefSet }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "aImgSet", scope = EnrollmentAnnotatedRef.class)
    public JAXBElement<AnnotatedImageRefSet> createEnrollmentAnnotatedRefAImgSet(AnnotatedImageRefSet value) {
        return new JAXBElement<AnnotatedImageRefSet>(_EnrollmentAnnotatedAImgSet_QNAME, AnnotatedImageRefSet.class, EnrollmentAnnotatedRef.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = EnrollmentAnnotatedRef.class)
    public JAXBElement<String> createEnrollmentAnnotatedRefAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, EnrollmentAnnotatedRef.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "jobId", scope = StartDBEnrollment.class)
    public JAXBElement<String> createStartDBEnrollmentJobId(String value) {
        return new JAXBElement<String>(_StartDBEnrollmentJobId_QNAME, String.class, StartDBEnrollment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "jobId", scope = StartDBIdentification.class)
    public JAXBElement<String> createStartDBIdentificationJobId(String value) {
        return new JAXBElement<String>(_StartDBEnrollmentJobId_QNAME, String.class, StartDBIdentification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "facility", scope = StartDBIdentification.class)
    public JAXBElement<String> createStartDBIdentificationFacility(String value) {
        return new JAXBElement<String>(_StartDBIdentificationFacility_QNAME, String.class, StartDBIdentification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "facility", scope = WaitForDBIdentification.class)
    public JAXBElement<String> createWaitForDBIdentificationFacility(String value) {
        return new JAXBElement<String>(_StartDBIdentificationFacility_QNAME, String.class, WaitForDBIdentification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = IdentificationCaseID.class)
    public JAXBElement<String> createIdentificationCaseIDCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, IdentificationCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationCaseID.class)
    public JAXBElement<String> createIdentificationCaseIDAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "image", scope = Identification.class)
    public JAXBElement<Image> createIdentificationImage(Image value) {
        return new JAXBElement<Image>(_FindFacesImage_QNAME, Image.class, Identification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = Identification.class)
    public JAXBElement<String> createIdentificationAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, Identification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImage", scope = IdentificationAnnotated.class)
    public JAXBElement<AnnotatedImage> createIdentificationAnnotatedAnnotatedImage(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_AnalyzePortraitAnnotatedAnnotatedImage_QNAME, AnnotatedImage.class, IdentificationAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationAnnotated.class)
    public JAXBElement<String> createIdentificationAnnotatedAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = IdentificationOne2FewCaseID.class)
    public JAXBElement<String> createIdentificationOne2FewCaseIDCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, IdentificationOne2FewCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "selectedCases", scope = IdentificationOne2FewCaseID.class)
    public JAXBElement<StringList> createIdentificationOne2FewCaseIDSelectedCases(StringList value) {
        return new JAXBElement<StringList>(_IdentificationOne2FewCaseIDSelectedCases_QNAME, StringList.class, IdentificationOne2FewCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationOne2FewCaseID.class)
    public JAXBElement<String> createIdentificationOne2FewCaseIDAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationOne2FewCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "image", scope = IdentificationOne2Few.class)
    public JAXBElement<Image> createIdentificationOne2FewImage(Image value) {
        return new JAXBElement<Image>(_FindFacesImage_QNAME, Image.class, IdentificationOne2Few.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "selectedCases", scope = IdentificationOne2Few.class)
    public JAXBElement<StringList> createIdentificationOne2FewSelectedCases(StringList value) {
        return new JAXBElement<StringList>(_IdentificationOne2FewCaseIDSelectedCases_QNAME, StringList.class, IdentificationOne2Few.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationOne2Few.class)
    public JAXBElement<String> createIdentificationOne2FewAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationOne2Few.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImage", scope = IdentificationOne2FewAnnotated.class)
    public JAXBElement<AnnotatedImage> createIdentificationOne2FewAnnotatedAnnotatedImage(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_AnalyzePortraitAnnotatedAnnotatedImage_QNAME, AnnotatedImage.class, IdentificationOne2FewAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StringList }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "selectedCases", scope = IdentificationOne2FewAnnotated.class)
    public JAXBElement<StringList> createIdentificationOne2FewAnnotatedSelectedCases(StringList value) {
        return new JAXBElement<StringList>(_IdentificationOne2FewCaseIDSelectedCases_QNAME, StringList.class, IdentificationOne2FewAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationOne2FewAnnotated.class)
    public JAXBElement<String> createIdentificationOne2FewAnnotatedAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationOne2FewAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = IdentificationBinningCaseID.class)
    public JAXBElement<String> createIdentificationBinningCaseIDCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, IdentificationBinningCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "binningSQL", scope = IdentificationBinningCaseID.class)
    public JAXBElement<String> createIdentificationBinningCaseIDBinningSQL(String value) {
        return new JAXBElement<String>(_IdentificationBinningCaseIDBinningSQL_QNAME, String.class, IdentificationBinningCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationBinningCaseID.class)
    public JAXBElement<String> createIdentificationBinningCaseIDAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationBinningCaseID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "image", scope = IdentificationBinning.class)
    public JAXBElement<Image> createIdentificationBinningImage(Image value) {
        return new JAXBElement<Image>(_FindFacesImage_QNAME, Image.class, IdentificationBinning.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "binningSQL", scope = IdentificationBinning.class)
    public JAXBElement<String> createIdentificationBinningBinningSQL(String value) {
        return new JAXBElement<String>(_IdentificationBinningCaseIDBinningSQL_QNAME, String.class, IdentificationBinning.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationBinning.class)
    public JAXBElement<String> createIdentificationBinningAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationBinning.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImage", scope = IdentificationBinningAnnotated.class)
    public JAXBElement<AnnotatedImage> createIdentificationBinningAnnotatedAnnotatedImage(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_AnalyzePortraitAnnotatedAnnotatedImage_QNAME, AnnotatedImage.class, IdentificationBinningAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "binningSQL", scope = IdentificationBinningAnnotated.class)
    public JAXBElement<String> createIdentificationBinningAnnotatedBinningSQL(String value) {
        return new JAXBElement<String>(_IdentificationBinningCaseIDBinningSQL_QNAME, String.class, IdentificationBinningAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = IdentificationBinningAnnotated.class)
    public JAXBElement<String> createIdentificationBinningAnnotatedAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, IdentificationBinningAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = Verification.class)
    public JAXBElement<String> createVerificationCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, Verification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "image", scope = Verification.class)
    public JAXBElement<Image> createVerificationImage(Image value) {
        return new JAXBElement<Image>(_FindFacesImage_QNAME, Image.class, Verification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = Verification.class)
    public JAXBElement<String> createVerificationAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, Verification.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "caseID", scope = VerificationAnnotated.class)
    public JAXBElement<String> createVerificationAnnotatedCaseID(String value) {
        return new JAXBElement<String>(_FvdbAddCaseCaseID_QNAME, String.class, VerificationAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImage", scope = VerificationAnnotated.class)
    public JAXBElement<AnnotatedImage> createVerificationAnnotatedAnnotatedImage(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_AnalyzePortraitAnnotatedAnnotatedImage_QNAME, AnnotatedImage.class, VerificationAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = VerificationAnnotated.class)
    public JAXBElement<String> createVerificationAnnotatedAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, VerificationAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "imageA", scope = VerificationPortraits.class)
    public JAXBElement<Image> createVerificationPortraitsImageA(Image value) {
        return new JAXBElement<Image>(_VerificationPortraitsImageA_QNAME, Image.class, VerificationPortraits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Image }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "imageB", scope = VerificationPortraits.class)
    public JAXBElement<Image> createVerificationPortraitsImageB(Image value) {
        return new JAXBElement<Image>(_VerificationPortraitsImageB_QNAME, Image.class, VerificationPortraits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = VerificationPortraits.class)
    public JAXBElement<String> createVerificationPortraitsAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, VerificationPortraits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImageA", scope = VerificationPortraitsAnnotated.class)
    public JAXBElement<AnnotatedImage> createVerificationPortraitsAnnotatedAnnotatedImageA(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_VerificationPortraitsAnnotatedAnnotatedImageA_QNAME, AnnotatedImage.class, VerificationPortraitsAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "annotatedImageB", scope = VerificationPortraitsAnnotated.class)
    public JAXBElement<AnnotatedImage> createVerificationPortraitsAnnotatedAnnotatedImageB(AnnotatedImage value) {
        return new JAXBElement<AnnotatedImage>(_VerificationPortraitsAnnotatedAnnotatedImageB_QNAME, AnnotatedImage.class, VerificationPortraitsAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "authName", scope = VerificationPortraitsAnnotated.class)
    public JAXBElement<String> createVerificationPortraitsAnnotatedAuthName(String value) {
        return new JAXBElement<String>(_EnrollmentDbAuthName_QNAME, String.class, VerificationPortraitsAnnotated.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaceLocation }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link FaceLocation }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "location", scope = EstimateEyesPositions.class)
    public JAXBElement<FaceLocation> createEstimateEyesPositionsLocation(FaceLocation value) {
        return new JAXBElement<FaceLocation>(_EstimateEyesPositionsLocation_QNAME, FaceLocation.class, EstimateEyesPositions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EyesPos }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link EyesPos }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "eyes", scope = CreateManualAnnotatedFaceLocation.class)
    public JAXBElement<EyesPos> createCreateManualAnnotatedFaceLocationEyes(EyesPos value) {
        return new JAXBElement<EyesPos>(_CreateManualAnnotatedFaceLocationEyes_QNAME, EyesPos.class, CreateManualAnnotatedFaceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "id", scope = CreateManualAnnotatedFaceLocation.class)
    public JAXBElement<String> createCreateManualAnnotatedFaceLocationId(String value) {
        return new JAXBElement<String>(_CreateManualAnnotatedFaceLocationId_QNAME, String.class, CreateManualAnnotatedFaceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "rightEye", scope = FaceLocation.class)
    public JAXBElement<Position> createFaceLocationRightEye(Position value) {
        return new JAXBElement<Position>(_FaceLocationRightEye_QNAME, Position.class, FaceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "leftEye", scope = FaceLocation.class)
    public JAXBElement<Position> createFaceLocationLeftEye(Position value) {
        return new JAXBElement<Position>(_FaceLocationLeftEye_QNAME, Position.class, FaceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "noseTip", scope = FaceLocation.class)
    public JAXBElement<Position> createFaceLocationNoseTip(Position value) {
        return new JAXBElement<Position>(_FaceLocationNoseTip_QNAME, Position.class, FaceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "rightMouthCorner", scope = FaceLocation.class)
    public JAXBElement<Position> createFaceLocationRightMouthCorner(Position value) {
        return new JAXBElement<Position>(_FaceLocationRightMouthCorner_QNAME, Position.class, FaceLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Position }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", name = "leftMouthCorner", scope = FaceLocation.class)
    public JAXBElement<Position> createFaceLocationLeftMouthCorner(Position value) {
        return new JAXBElement<Position>(_FaceLocationLeftMouthCorner_QNAME, Position.class, FaceLocation.class, value);
    }

}
