//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ethnicity measurement
 * 
 * <p>Java class for PortraitEthnicityMeasurements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortraitEthnicityMeasurements"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="white" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="black" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="asian" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortraitEthnicityMeasurements", propOrder = {
    "white",
    "black",
    "asian"
})
public class PortraitEthnicityMeasurements {

    protected float white;
    protected float black;
    protected float asian;

    /**
     * Gets the value of the white property.
     * 
     */
    public float getWhite() {
        return white;
    }

    /**
     * Sets the value of the white property.
     * 
     */
    public void setWhite(float value) {
        this.white = value;
    }

    /**
     * Gets the value of the black property.
     * 
     */
    public float getBlack() {
        return black;
    }

    /**
     * Sets the value of the black property.
     * 
     */
    public void setBlack(float value) {
        this.black = value;
    }

    /**
     * Gets the value of the asian property.
     * 
     */
    public float getAsian() {
        return asian;
    }

    /**
     * Sets the value of the asian property.
     * 
     */
    public void setAsian(float value) {
        this.asian = value;
    }

}
