//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.*;


/**
 * portrait characteristics measurements
 * 
 * <p>Java class for PortraitCharacteristics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortraitCharacteristics"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isColor" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="rightEye" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position"/&gt;
 *         &lt;element name="eyeDistance" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="faceCenter" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position"/&gt;
 *         &lt;element name="numberOfFaces" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="leftEye" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Position"/&gt;
 *         &lt;element name="glasses" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="rightEyeOpen" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="leftEyeOpen" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="rightEyeGazeFrontal" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="leftEyeGazeFrontal" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="rightEyeRed" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="leftEyeRed" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="rightEyeTinted" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="leftEyeTinted" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="mouthClosed" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="exposure" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="grayScaleDensity" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/&gt;
 *         &lt;element name="naturalSkinColour" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="hotSpots" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="backgroundUniformity" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="widthOfHead" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="lengthOfHead" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="poseAngleRoll" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="chin" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="crown" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="rightEar" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="leftEar" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="deviationFromFrontalPose" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="isMale" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="deviationFromUniformLighting" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="sharpness" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="ethnicity" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}PortraitEthnicityMeasurements"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="under18" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="under21" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="faceMaskScore" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortraitCharacteristics", propOrder = {
    "isColor",
    "width",
    "height",
        "rightEye",
    "eyeDistance",
    "faceCenter",
    "numberOfFaces",
        "leftEye",
    "glasses",
        "rightEyeOpen",
        "leftEyeOpen",
        "rightEyeGazeFrontal",
        "leftEyeGazeFrontal",
        "rightEyeRed",
        "leftEyeRed",
        "rightEyeTinted",
        "leftEyeTinted",
    "mouthClosed",
    "exposure",
    "grayScaleDensity",
    "naturalSkinColour",
    "hotSpots",
    "backgroundUniformity",
    "widthOfHead",
    "lengthOfHead",
    "poseAngleRoll",
    "chin",
    "crown",
        "rightEar",
        "leftEar",
    "deviationFromFrontalPose",
    "isMale",
    "deviationFromUniformLighting",
    "sharpness",
    "ethnicity",
        "age",
        "under18",
        "under21",
        "faceMaskScore"
})
public class PortraitCharacteristics {

    protected boolean isColor;
    @XmlSchemaType(name = "unsignedInt")
    protected long width;
    @XmlSchemaType(name = "unsignedInt")
    protected long height;
    @XmlElement(required = true)
    protected Position rightEye;
    protected float eyeDistance;
    @XmlElement(required = true)
    protected Position faceCenter;
    @XmlSchemaType(name = "unsignedInt")
    protected long numberOfFaces;
    @XmlElement(required = true)
    protected Position leftEye;
    protected float glasses;
    protected float rightEyeOpen;
    protected float leftEyeOpen;
    protected float rightEyeGazeFrontal;
    protected float leftEyeGazeFrontal;
    protected float rightEyeRed;
    protected float leftEyeRed;
    protected float rightEyeTinted;
    protected float leftEyeTinted;
    protected float mouthClosed;
    protected float exposure;
    @XmlSchemaType(name = "unsignedInt")
    protected long grayScaleDensity;
    protected float naturalSkinColour;
    protected float hotSpots;
    protected float backgroundUniformity;
    protected float widthOfHead;
    protected float lengthOfHead;
    protected float poseAngleRoll;
    protected float chin;
    protected float crown;
    protected float rightEar;
    protected float leftEar;
    protected float deviationFromFrontalPose;
    protected float isMale;
    protected float deviationFromUniformLighting;
    protected float sharpness;
    @XmlElement(required = true)
    protected PortraitEthnicityMeasurements ethnicity;
    protected float age;
    protected float under18;
    protected float under21;
    protected float faceMaskScore;

    /**
     * Gets the value of the isColor property.
     * 
     */
    public boolean isIsColor() {
        return isColor;
    }

    /**
     * Sets the value of the isColor property.
     * 
     */
    public void setIsColor(boolean value) {
        this.isColor = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public long getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(long value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public long getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(long value) {
        this.height = value;
    }

    /**
     * Gets the value of the rightEye property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getRightEye() {
        return rightEye;
    }

    /**
     * Sets the value of the rightEye property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setRightEye(Position value) {
        this.rightEye = value;
    }

    /**
     * Gets the value of the eyeDistance property.
     * 
     */
    public float getEyeDistance() {
        return eyeDistance;
    }

    /**
     * Sets the value of the eyeDistance property.
     * 
     */
    public void setEyeDistance(float value) {
        this.eyeDistance = value;
    }

    /**
     * Gets the value of the faceCenter property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getFaceCenter() {
        return faceCenter;
    }

    /**
     * Sets the value of the faceCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setFaceCenter(Position value) {
        this.faceCenter = value;
    }

    /**
     * Gets the value of the numberOfFaces property.
     * 
     */
    public long getNumberOfFaces() {
        return numberOfFaces;
    }

    /**
     * Sets the value of the numberOfFaces property.
     * 
     */
    public void setNumberOfFaces(long value) {
        this.numberOfFaces = value;
    }

    /**
     * Gets the value of the leftEye property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getLeftEye() {
        return leftEye;
    }

    /**
     * Sets the value of the leftEye property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setLeftEye(Position value) {
        this.leftEye = value;
    }

    /**
     * Gets the value of the glasses property.
     * 
     */
    public float getGlasses() {
        return glasses;
    }

    /**
     * Sets the value of the glasses property.
     * 
     */
    public void setGlasses(float value) {
        this.glasses = value;
    }

    /**
     * Gets the value of the rightEyeOpen property.
     * 
     */
    public float getRightEyeOpen() {
        return rightEyeOpen;
    }

    /**
     * Sets the value of the rightEyeOpen property.
     * 
     */
    public void setRightEyeOpen(float value) {
        this.rightEyeOpen = value;
    }

    /**
     * Gets the value of the leftEyeOpen property.
     * 
     */
    public float getLeftEyeOpen() {
        return leftEyeOpen;
    }

    /**
     * Sets the value of the leftEyeOpen property.
     * 
     */
    public void setLeftEyeOpen(float value) {
        this.leftEyeOpen = value;
    }

    /**
     * Gets the value of the rightEyeGazeFrontal property.
     * 
     */
    public float getRightEyeGazeFrontal() {
        return rightEyeGazeFrontal;
    }

    /**
     * Sets the value of the rightEyeGazeFrontal property.
     * 
     */
    public void setRightEyeGazeFrontal(float value) {
        this.rightEyeGazeFrontal = value;
    }

    /**
     * Gets the value of the leftEyeGazeFrontal property.
     * 
     */
    public float getLeftEyeGazeFrontal() {
        return leftEyeGazeFrontal;
    }

    /**
     * Sets the value of the leftEyeGazeFrontal property.
     * 
     */
    public void setLeftEyeGazeFrontal(float value) {
        this.leftEyeGazeFrontal = value;
    }

    /**
     * Gets the value of the rightEyeRed property.
     * 
     */
    public float getRightEyeRed() {
        return rightEyeRed;
    }

    /**
     * Sets the value of the rightEyeRed property.
     * 
     */
    public void setRightEyeRed(float value) {
        this.rightEyeRed = value;
    }

    /**
     * Gets the value of the leftEyeRed property.
     * 
     */
    public float getLeftEyeRed() {
        return leftEyeRed;
    }

    /**
     * Sets the value of the leftEyeRed property.
     * 
     */
    public void setLeftEyeRed(float value) {
        this.leftEyeRed = value;
    }

    /**
     * Gets the value of the rightEyeTinted property.
     * 
     */
    public float getRightEyeTinted() {
        return rightEyeTinted;
    }

    /**
     * Sets the value of the rightEyeTinted property.
     * 
     */
    public void setRightEyeTinted(float value) {
        this.rightEyeTinted = value;
    }

    /**
     * Gets the value of the leftEyeTinted property.
     * 
     */
    public float getLeftEyeTinted() {
        return leftEyeTinted;
    }

    /**
     * Sets the value of the leftEyeTinted property.
     * 
     */
    public void setLeftEyeTinted(float value) {
        this.leftEyeTinted = value;
    }

    /**
     * Gets the value of the mouthClosed property.
     * 
     */
    public float getMouthClosed() {
        return mouthClosed;
    }

    /**
     * Sets the value of the mouthClosed property.
     * 
     */
    public void setMouthClosed(float value) {
        this.mouthClosed = value;
    }

    /**
     * Gets the value of the exposure property.
     * 
     */
    public float getExposure() {
        return exposure;
    }

    /**
     * Sets the value of the exposure property.
     * 
     */
    public void setExposure(float value) {
        this.exposure = value;
    }

    /**
     * Gets the value of the grayScaleDensity property.
     * 
     */
    public long getGrayScaleDensity() {
        return grayScaleDensity;
    }

    /**
     * Sets the value of the grayScaleDensity property.
     * 
     */
    public void setGrayScaleDensity(long value) {
        this.grayScaleDensity = value;
    }

    /**
     * Gets the value of the naturalSkinColour property.
     * 
     */
    public float getNaturalSkinColour() {
        return naturalSkinColour;
    }

    /**
     * Sets the value of the naturalSkinColour property.
     * 
     */
    public void setNaturalSkinColour(float value) {
        this.naturalSkinColour = value;
    }

    /**
     * Gets the value of the hotSpots property.
     * 
     */
    public float getHotSpots() {
        return hotSpots;
    }

    /**
     * Sets the value of the hotSpots property.
     * 
     */
    public void setHotSpots(float value) {
        this.hotSpots = value;
    }

    /**
     * Gets the value of the backgroundUniformity property.
     * 
     */
    public float getBackgroundUniformity() {
        return backgroundUniformity;
    }

    /**
     * Sets the value of the backgroundUniformity property.
     * 
     */
    public void setBackgroundUniformity(float value) {
        this.backgroundUniformity = value;
    }

    /**
     * Gets the value of the widthOfHead property.
     * 
     */
    public float getWidthOfHead() {
        return widthOfHead;
    }

    /**
     * Sets the value of the widthOfHead property.
     * 
     */
    public void setWidthOfHead(float value) {
        this.widthOfHead = value;
    }

    /**
     * Gets the value of the lengthOfHead property.
     * 
     */
    public float getLengthOfHead() {
        return lengthOfHead;
    }

    /**
     * Sets the value of the lengthOfHead property.
     * 
     */
    public void setLengthOfHead(float value) {
        this.lengthOfHead = value;
    }

    /**
     * Gets the value of the poseAngleRoll property.
     * 
     */
    public float getPoseAngleRoll() {
        return poseAngleRoll;
    }

    /**
     * Sets the value of the poseAngleRoll property.
     * 
     */
    public void setPoseAngleRoll(float value) {
        this.poseAngleRoll = value;
    }

    /**
     * Gets the value of the chin property.
     * 
     */
    public float getChin() {
        return chin;
    }

    /**
     * Sets the value of the chin property.
     * 
     */
    public void setChin(float value) {
        this.chin = value;
    }

    /**
     * Gets the value of the crown property.
     * 
     */
    public float getCrown() {
        return crown;
    }

    /**
     * Sets the value of the crown property.
     * 
     */
    public void setCrown(float value) {
        this.crown = value;
    }

    /**
     * Gets the value of the rightEar property.
     * 
     */
    public float getRightEar() {
        return rightEar;
    }

    /**
     * Sets the value of the rightEar property.
     * 
     */
    public void setRightEar(float value) {
        this.rightEar = value;
    }

    /**
     * Gets the value of the leftEar property.
     * 
     */
    public float getLeftEar() {
        return leftEar;
    }

    /**
     * Sets the value of the leftEar property.
     * 
     */
    public void setLeftEar(float value) {
        this.leftEar = value;
    }

    /**
     * Gets the value of the deviationFromFrontalPose property.
     * 
     */
    public float getDeviationFromFrontalPose() {
        return deviationFromFrontalPose;
    }

    /**
     * Sets the value of the deviationFromFrontalPose property.
     * 
     */
    public void setDeviationFromFrontalPose(float value) {
        this.deviationFromFrontalPose = value;
    }

    /**
     * Gets the value of the isMale property.
     * 
     */
    public float getIsMale() {
        return isMale;
    }

    /**
     * Sets the value of the isMale property.
     * 
     */
    public void setIsMale(float value) {
        this.isMale = value;
    }

    /**
     * Gets the value of the deviationFromUniformLighting property.
     * 
     */
    public float getDeviationFromUniformLighting() {
        return deviationFromUniformLighting;
    }

    /**
     * Sets the value of the deviationFromUniformLighting property.
     * 
     */
    public void setDeviationFromUniformLighting(float value) {
        this.deviationFromUniformLighting = value;
    }

    /**
     * Gets the value of the sharpness property.
     * 
     */
    public float getSharpness() {
        return sharpness;
    }

    /**
     * Sets the value of the sharpness property.
     * 
     */
    public void setSharpness(float value) {
        this.sharpness = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link PortraitEthnicityMeasurements }
     *     
     */
    public PortraitEthnicityMeasurements getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortraitEthnicityMeasurements }
     *     
     */
    public void setEthnicity(PortraitEthnicityMeasurements value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the age property.
     * 
     */
    public float getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(float value) {
        this.age = value;
    }

    /**
     * Gets the value of the under18 property.
     */
    public float getUnder18() {
        return under18;
    }

    /**
     * Sets the value of the under18 property.
     */
    public void setUnder18(float value) {
        this.under18 = value;
    }

    /**
     * Gets the value of the under21 property.
     */
    public float getUnder21() {
        return under21;
    }

    /**
     * Sets the value of the under21 property.
     */
    public void setUnder21(float value) {
        this.under21 = value;
    }

    /**
     * Gets the value of the faceMaskScore property.
     */
    public float getFaceMaskScore() {
        return faceMaskScore;
    }

    /**
     * Sets the value of the faceMaskScore property.
     */
    public void setFaceMaskScore(float value) {
        this.faceMaskScore = value;
    }

}
