//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.*;


/**
 * portrait feature set
 * 
 * <p>Java class for PortraitFeatureSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortraitFeatureSet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="wearsGlasses" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="gender" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Gender"/&gt;
 *         &lt;element name="ethnicity" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}Ethnicity"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="under18" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="under21" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="wearsFaceMask" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortraitFeatureSet", propOrder = {
    "wearsGlasses",
    "gender",
    "ethnicity",
        "age",
        "under18",
        "under21",
        "wearsFaceMask"
})
public class PortraitFeatureSet {

    protected boolean wearsGlasses;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Gender gender;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Ethnicity ethnicity;
    protected float age;
    protected boolean under18;
    protected boolean under21;
    protected boolean wearsFaceMask;

    /**
     * Gets the value of the wearsGlasses property.
     * 
     */
    public boolean isWearsGlasses() {
        return wearsGlasses;
    }

    /**
     * Sets the value of the wearsGlasses property.
     * 
     */
    public void setWearsGlasses(boolean value) {
        this.wearsGlasses = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link Ethnicity }
     *     
     */
    public Ethnicity getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ethnicity }
     *     
     */
    public void setEthnicity(Ethnicity value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the age property.
     * 
     */
    public float getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(float value) {
        this.age = value;
    }

    /**
     * Gets the value of the under18 property.
     */
    public boolean isUnder18() {
        return under18;
    }

    /**
     * Sets the value of the under18 property.
     */
    public void setUnder18(boolean value) {
        this.under18 = value;
    }

    /**
     * Gets the value of the under21 property.
     */
    public boolean isUnder21() {
        return under21;
    }

    /**
     * Sets the value of the under21 property.
     */
    public void setUnder21(boolean value) {
        this.under21 = value;
    }

    /**
     * Gets the value of the wearsFaceMask property.
     */
    public boolean isWearsFaceMask() {
        return wearsFaceMask;
    }

    /**
     * Sets the value of the wearsFaceMask property.
     */
    public void setWearsFaceMask(boolean value) {
        this.wearsFaceMask = value;
    }

}
