//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerificationResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerificationResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="notEnrolled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="processedImage" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}ImageProcessingInfo"/&gt;
 *         &lt;element name="successfulVerified" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerificationResult", propOrder = {
    "transactionId",
    "notEnrolled",
    "processedImage",
    "successfulVerified",
    "score"
})
public class VerificationResult {

    @XmlElement(required = true)
    protected String transactionId;
    protected boolean notEnrolled;
    @XmlElement(required = true)
    protected ImageProcessingInfo processedImage;
    protected boolean successfulVerified;
    protected float score;

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the notEnrolled property.
     * 
     */
    public boolean isNotEnrolled() {
        return notEnrolled;
    }

    /**
     * Sets the value of the notEnrolled property.
     * 
     */
    public void setNotEnrolled(boolean value) {
        this.notEnrolled = value;
    }

    /**
     * Gets the value of the processedImage property.
     * 
     * @return
     *     possible object is
     *     {@link ImageProcessingInfo }
     *     
     */
    public ImageProcessingInfo getProcessedImage() {
        return processedImage;
    }

    /**
     * Sets the value of the processedImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageProcessingInfo }
     *     
     */
    public void setProcessedImage(ImageProcessingInfo value) {
        this.processedImage = value;
    }

    /**
     * Gets the value of the successfulVerified property.
     * 
     */
    public boolean isSuccessfulVerified() {
        return successfulVerified;
    }

    /**
     * Sets the value of the successfulVerified property.
     * 
     */
    public void setSuccessfulVerified(boolean value) {
        this.successfulVerified = value;
    }

    /**
     * Gets the value of the score property.
     * 
     */
    public float getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     */
    public void setScore(float value) {
        this.score = value;
    }

}
