//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.13 at 09:28:36 AM CEST 
//


package com.cognitec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="annotatedImageA" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}AnnotatedImage" minOccurs="0"/&gt;
 *         &lt;element name="annotatedImageB" type="{urn:cognitec.com/DBScanID/WS/2.6/XMLSchema}AnnotatedImage" minOccurs="0"/&gt;
 *         &lt;element name="authName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotatedImageA",
    "annotatedImageB",
    "authName"
})
@XmlRootElement(name = "verification-portraits-annotated")
public class VerificationPortraitsAnnotated {

    @XmlElementRef(name = "annotatedImageA", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<AnnotatedImage> annotatedImageA;
    @XmlElementRef(name = "annotatedImageB", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<AnnotatedImage> annotatedImageB;
    @XmlElementRef(name = "authName", namespace = "urn:cognitec.com/DBScanID/WS/2.6/XMLSchema", type = JAXBElement.class, required = false)
    protected JAXBElement<String> authName;

    /**
     * Gets the value of the annotatedImageA property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *     
     */
    public JAXBElement<AnnotatedImage> getAnnotatedImageA() {
        return annotatedImageA;
    }

    /**
     * Sets the value of the annotatedImageA property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *     
     */
    public void setAnnotatedImageA(JAXBElement<AnnotatedImage> value) {
        this.annotatedImageA = value;
    }

    /**
     * Gets the value of the annotatedImageB property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *     
     */
    public JAXBElement<AnnotatedImage> getAnnotatedImageB() {
        return annotatedImageB;
    }

    /**
     * Sets the value of the annotatedImageB property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AnnotatedImage }{@code >}
     *     
     */
    public void setAnnotatedImageB(JAXBElement<AnnotatedImage> value) {
        this.annotatedImageB = value;
    }

    /**
     * Gets the value of the authName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAuthName() {
        return authName;
    }

    /**
     * Sets the value of the authName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAuthName(JAXBElement<String> value) {
        this.authName = value;
    }

}
