connect cogni/cogni123;

CREATE TABLE COGNI.BILD_DELETED (
    OID NUMBER(10), 
    DATE_MODIFIED DATE, 
    CONSTRAINT BILD_DELETED_PK PRIMARY KEY (OID) USING INDEX
);

GRANT SELECT, DELETE ON COGNI.BILD_DELETED TO LIBIASNEW;

disconnect;